const titleDescriptions = [
	"AKC Prefix", "Field Trial", "AFC", "Amateur Field Champion",
	"AKC Prefix", "Agility Trial", "AGCH", "Agility Grand Champion",
	"AKC Prefix", "Coonhound Bench Show", "CCH", "Bench Show Champion",
	"AKC Prefix", "Coonhound Field Trial", "CFC", "Coonhound Field Champion",
	"AKC Prefix", "Coonhound Bench Show", "CGCH", "Coonhound Grand Champion",
	"AKC Prefix", "Coonhound Field Trial", "CGF", "Coonhound Grand Field Champion",
	"AKC Prefix", "Coonhound Nite Hunt", "CGN", "Grand Nite Champion",
	"AKC Prefix", "Coonhound Water Race", "CGW", "Grand Water Race Champion",
	"AKC Prefix", "Conformation", "CH", "Champion",
	"AKC Prefix", "Coonhound Nite Hunt", "CNC", "Nite Champion",
	"AKC Prefix", "Coonhound Bench Show", "CSG", "Supreme Grand Champion",
	"AKC Prefix", "Coonhound Field Trial", "CSGF", "Supreme Grand Field Champion",
	"AKC Prefix", "Coonhound Nite Hunt", "CSGN", "Supreme Grand Nite Champion",
	"AKC Prefix", "Coonhound Water Race", "CSGW", "Supreme Grand Water Race Champion",
	"AKC Prefix", "Tracking Test", "CT", "Champion Tracker",
	"AKC Prefix", "Coonhound Water Race", "CWC", "Water Race Champion",
	"AKC Prefix", "Coonhound Bench Show", "CWSG", "World Show Champion",
	"AKC Prefix", "Conformation AND Field Trial or Herding Trial", "DC", "Dual Champion",
	"AKC Prefix", "Field Trial", "FC", "Field Champion",
	"AKC Prefix", "Conformation", "GCH", "Grand Champion",
	"AKC Prefix", "Conformation", "GCHB", "Grand Champion Bronze",
	"AKC Prefix", "Conformation", "GCHG", "Grand Champion Gold",
	"AKC Prefix", "Conformation", "GCHP", "Grand Champion Platinum",
	"AKC Prefix", "Conformation", "GCHS", "Grand Champion Silver",
	"AKC Prefix", "Field Trial", "GDSC", "Gun Dog Stake Champion",
	"AKC Prefix", "Field Trial", "GAFC", "Grand Amateur Field Champion",
	"AKC Prefix", "Field Trial", "GFC", "Grand Field Champion",
	"AKC Prefix", "Herding Trial", "HC", "Herding Champion",
	"AKC Prefix", "Agility Trial", "MACH", "Master Agility Champion",
	"AKC Prefix", "National Agility Championship", "NAC", "National Agility Champion",
	"AKC Prefix", "Field Trial", "NAFC", "National Amateur Field Champion",
	"AKC Prefix", "Field Trial", "NAGDC", "National Amateur Gundog Champion",
	"AKC Prefix", "Field Trial", "NFC", "National Field Champion",
	"AKC Prefix", "Field Trial", "NGDC", "National Gundog Champion",
	"AKC Prefix", "National Obedience Invitational", "NOC", "National Obedience Champion",
	"AKC Prefix", "Obedience Trial", "OTCH", "Obedience Trial Champion",
	"AKC Prefix", "Agility Trial", "PACH", "Preferred Agility Champion",
	"AKC Prefix", "National Agility Championship", "PNAC", "Preferred National Agility Champion",
	"AKC Prefix", "Obedience Trial", "POC", "Preferred Obedience Champion",
	"AKC Prefix", "Rally Trial", "RACH", "AKC Rally Champion",
	"AKC Prefix", "Field Trial", "RGDSC", "Retrieving Gun Dog Stake Champion",
	"AKC Prefix", "AKC Rally National Championship", "RNC", "AKC Rally National Champion",
	"AKC Prefix", "Conformation AND Herding Trial or Field Trial AND Obedience Trial or Tracking Trial or Agility Trial", "TC", "Triple Champion",
	"AKC Prefix", "Tracking Test AND Obedience Trial or Agility Trial", "VCCH", "Versatile Companion Champion",
	"AKC Prefix", "Coonhound Nite Hunt", "WNC", "World Nite Champion",
	"AKC Suffix", "Agility Test", "ACT1", "Agility Course Test 1",
	"AKC Suffix", "Agility Test", "ACT2", "Agility Course Test 2",
	"AKC Suffix", "Agility Test", "ACT1J", "Agility Course Test 1 Jumpers",
	"AKC Suffix", "Agility Test", "ACT2J", "Agility Course Test 2 Jumpers",
	"AKC Suffix", "Agility Trial", "AJP", "Excellent Agility Jumpers With Weaves “A” Preferred",
	"AKC Suffix", "Temperament Test", "ATT", "AKC Temperament Test",
	"AKC Suffix", "Aglity Trial", "AX", "Agility Excellent",
	"AKC Suffix", "Agility Trial", "AXJ", "Excellent Agility Jumper",
	"AKC Suffix", "Agility Trial", "AXP", "Agility Excellent “A” Preferred",
	"AKC Suffix", "Fast CAT", "BCAT", "Fast CAT BCAT",
	"AKC Suffix", "Obedience Trial", "BN", "Beginner Novice",
	"AKC Suffix", "Virtual Obedience Test", "BN-V", "Virtual Beginner Novice",
	"AKC Suffix", "Coursing Ability Test", "CA", "Coursing Ability",
	"AKC Suffix", "Coursing Ability Test", "CAA", "Coursing Ability Advanced",
	"AKC Suffix", "Coursing Ability Test", "CAX", "Coursing Ability Excellent",
	"AKC Suffix", "Coursing Ability Test", "CAX2", "Coursing Ability Excellent 2",
	"AKC Suffix", "Obedience Trial", "CD", "Companion Dog",
	"AKC Suffix", "Virtual Obedience Test", "CD-V", "Virtual Companion Dog",
	"AKC Suffix", "Obedience Trial", "CDX", "Companion Dog Excellent",
	"AKC Suffix", "Canine Good Citizen", "CGC", "Canine Good Citizen",
	"AKC Suffix", "Canine Good Citizen", "CGCA", "AKC Community Canine",
	"AKC Suffix", "Canine Good Citizen", "CGCU", "Canine Good Citizen Urban",
	"AKC Suffix", "Conformation", "CM", "Certificate of Merit",
	"AKC Suffix", "Fast CAT", "DCAT", "Fast CAT DCAT",
	"AKC Suffix", "Earthdog", "EE", "Endurance Earthdog",
	"AKC Suffix", "Fast CAT", "FCAT", "Fast CAT® FCAT",
	"AKC Suffix", "Farm Dog Test", "FDC", "Farm Dog Certified",
	"AKC Suffix", "Agility Trial", "FTC", "FAST Century",
	"AKC Suffix", "Agility Trial", "FTCP", "FAST Century Preferred",
	"AKC Suffix", "Obedience Trial", "GN", "Graduate Novice",
	"AKC Suffix", "Obedience Trial", "GO", "Graduate Open",
	"AKC Suffix", "Herding Trial", "HI", "Herding Intermediate",
	"AKC Suffix", "Herding Trial", "HIAdsc", "Herding Intermediate Course A (ducks, sheep, cattle)",
	"AKC Suffix", "Herding Trial", "HIBdsc", "Herding Intermediate Course B (ducks, sheep, cattle)",
	"AKC Suffix", "Herding Trial", "HICs", "Herding Intermediate Course C (sheep)",
	"AKC Suffix", "Herding Trial", "HS", "Herding Started",
	"AKC Suffix", "Herding Trial", "HSAdsc", "Herding Started Course A (ducks, sheep, cattle)",
	"AKC Suffix", "Herding Trial", "HSBdsc", "Herding Started Course B (ducks, sheep, cattle)",
	"AKC Suffix", "Herding Trial", "HSCs", "Herding Started Course C (sheep)",
	"AKC Suffix", "Herding Trial", "HT", "Herding Tested",
	"AKC Suffix", "Herding Trial", "HX", "Herding Excellent",
	"AKC Suffix", "Herding Trial", "HXAdsc", "Herding Advanced Course A (ducks, sheep, cattle)",
	"AKC Suffix", "Herding Trial", "HXBdsc", "Herding Advanced Course B (ducks, sheep, cattle)",
	"AKC Suffix", "Herding Trial", "HXCs", "Herding Advanced Course C (sheep)",
	"AKC Suffix", "Lure Coursing", "JC", "Junior Courser",
	"AKC Suffix", "Earthdog", "JE", "Junior Earthdog",
	"AKC Suffix", "Hunting Test", "JH", "Junior Hunter",
	"AKC Suffix", "Hunting Test", "JHA", "Junior Hunter Advanced",
	"AKC Suffix", "Hunting Test", "JHR", "Junior Hunter Retriever",
	"AKC Suffix", "Hunting Test", "JHU", "Junior Hunter Upland",
	"AKC Suffix", "Lure Coursing", "LCx", "", "Lure Courser Excellent",
	"AKC Suffix", "Lure Coursing", "MC", "Master Courser",
	"AKC Suffix", "Earthdog", "ME", "Master Earthdog",
	"AKC Suffix", "Agility Trial", "MFB", "Master Bronze FAST",
	"AKC Suffix", "Agility Trial", "MFC", "Master Century FAST",
	"AKC Suffix", "Agility Trial", "MFG", "Master Gold FAST",
	"AKC Suffix", "Agility Trial", "MFP", "Master Excellent FAST Preferred",
	"AKC Suffix", "Agility Trial", "MFPB", "Master Bronze FAST Preferred",
	"AKC Suffix", "Agility Trial", "MFPC", "Master Century FAST Preferred",
	"AKC Suffix", "Agility Trial", "MFPG", "Master Gold FAST Preferred",
	"AKC Suffix", "Agility Trial", "MFPS", "Master Silver FAST Preferred",
	"AKC Suffix", "Agility Trial", "MFS", "Master Silver FAST",
	"AKC Suffix", "Hunting Test", "MH", "Master Hunter",
	"AKC Suffix", "Hunting Test", "MHA", "Master Hunter Advanced",
	"AKC Suffix", "Hunting Test", "MHR", "Master Hunter Retriever",
	"AKC Suffix", "Hunting Test", "MHU", "Master Hunter Upland",
	"AKC Suffix", "Agility Trial", "MJB", "Master Bronze Jumpers With Weaves",
	"AKC Suffix", "Agility Trial", "MJC", "Master Century Jumpers With Weaves",
	"AKC Suffix", "Agility Trial", "MJG", "Master Gold Jumpers With Weaves",
	"AKC Suffix", "Agility Trial", "MJP", "Master Excellent Jumpers With Weaves Preferred",
	"AKC Suffix", "Agility Trial", "MJPB", "Master Bronze Jumper With Weaves Preferred",
	"AKC Suffix", "Agility Trial", "MJPC", "Master Century Jumper With Weaves Preferred",
	"AKC Suffix", "Agility Trial", "MJPG", "Master Gold Jumper With Weaves Preferred",
	"AKC Suffix", "Agility Trial", "MJPS", "Master Silver Jumper With Weaves Preferred",
	"AKC Suffix", "Agility Trial", "MJS", "Master Silver Jumpers With Weaves",
	"AKC Suffix", "Hunting Test", "MNH", "Master National Hunter",
	"AKC Suffix", "Agility Trial", "MX", "Master Agility Excellent",
	"AKC Suffix", "Agility Trial", "MXB", "Master Bronze Agility",
	"AKC Suffix", "Agility Trial", "MXC", "Master Century Agility",
	"AKC Suffix", "Agility Trial", "MXF", "Master Excellent FAST",
	"AKC Suffix", "Agility Trial", "MXG", "Master Gold Agility",
	"AKC Suffix", "Agility Trial", "MXJ", "Master Excellent Jumpers With Weaves",
	"AKC Suffix", "Agility Trial", "MXP", "Master Agility Excellent Preferred",
	"AKC Suffix", "Agility Trial", "MXPB", "Master Bronze Agility Preferred",
	"AKC Suffix", "Agility Trial", "MXPC", "Master Century Agility Preferred",
	"AKC Suffix", "Agility Trial", "MXPG", "Master Gold Agility Preferred",
	"AKC Suffix", "Agility Trial", "MXPS", "Master Silver Agility Preferred",
	"AKC Suffix", "Agility Trial", "MXS", "Master Silver Agility",
	"AKC Suffix", "Agility Trial", "NA", "Novice Agility",
	"AKC Suffix", "Agility Trial", "NAJ", "Novice Agility Jumper",
	"AKC Suffix", "Agility Trial", "NAP", "Novice Agility Preferred",
	"AKC Suffix", "Agility Trial", "NF", "Novice FAST",
	"AKC Suffix", "Agility Trial", "NFP", "Novice FAST Preferred",
	"AKC Suffix", "Agility Trial", "NJP", "Novice Jumpers With Weaves Preferred",
	"AKC Suffix", "Agility Trial", "OA", "Open Agility",
	"AKC Suffix", "Agility Trial", "OAJ", "Open Agility Jumper",
	"AKC Suffix", "Agility Trial", "OAP", "Open Agility Preferred",
	"AKC Suffix", "Agility Trial", "OF", "Open FAST",
	"AKC Suffix", "Agility Trial", "OFP", "Open FAST Preferred",
	"AKC Suffix", "Agility Trial", "OGM", "Obedience Grand Master",
	"AKC Suffix", "Agility Trial", "OJP", "Open Jumpers With Weaves Preferred",
	"AKC Suffix", "Obedience Trial", "OM", "Obedience Master",
	"AKC Suffix", "Agility Trial", "PAD", "Premier Agility Dog",
	"AKC Suffix", "Agility Trial", "PADP", "Premier Agility Dog Preferred",
	"AKC Suffix", "Agility Trial", "PAX", "Preferred Agility Excellent",
	"AKC Suffix", "Obedience Trial", "PCD", "Preferred Companion Dog",
	"AKC Suffix", "Obedience Trial", "PCDX", "Preferred Companion Dog Excellent",
	"AKC Suffix", "Agility Trial", "PDB", "Premier Agility Dog Bronze",
	"AKC Suffix", "Agility Trial", "PDBP", "Premier Agility Dog Bronze Preferred",
	"AKC Suffix", "Agility Trial", "PDC", "Premier Agility Dog Century",
	"AKC Suffix", "Agility Trial", "PDCP", "Premier Agility Dog Century Preferred",
	"AKC Suffix", "Agility Trial", "PDG", "Premier Agility Dog Gold",
	"AKC Suffix", "Agility Trial", "PDGP", "Premier Agility Dog Gold Preferred",
	"AKC Suffix", "Agility Trial", "PDS", "Premier Agility Dog Silver",
	"AKC Suffix", "Agility Trial", "PDSP", "Premier Agility Dog Silver Preferred",
	"AKC Suffix", "Agility Trial", "PJB", "Premier Jumpers Dog Bronze",
	"AKC Suffix", "Agility Trial", "PJBP", "Premier Jumpers Dog Bronze Preferred",
	"AKC Suffix", "Agility Trial", "PJC", "Premier Jumpers Dog Century",
	"AKC Suffix", "Agility Trial", "PJCP", "Premier Jumpers Dog Century Preferred",
	"AKC Suffix", "Agility Trial", "PJD", "Premier Jumpers Dog",
	"AKC Suffix", "Agility Trial", "PJDP", "Premier Jumpers Dog Preferred",
	"AKC Suffix", "Agility Trial", "PJG", "Premier Jumpers Dog Gold",
	"AKC Suffix", "Agility Trial", "PJGP", "Premier Jumpers Dog Gold Preferred",
	"AKC Suffix", "Agility Trial", "PJS", "Premier Jumpers Dog Silver",
	"AKC Suffix", "Agility Trial", "PJSP", "Premier Jumpers Dog Silver Preferred",
	"AKC Suffix", "Herding Trial", "PT", "Pre-Trial Tested",
	"AKC Suffix", "Obedience Trial", "PUDX", "Preferred Utility Dog Excellent",
	"AKC Suffix", "Obedience Trial", "PUTD", "Preferred Utility Dog",
	"AKC Suffix", "Rally Trial", "RN", "AKC Rally Novice",
	"AKC Suffix", "Rally Trial", "RA", "AKC Rally Advanced",
	"AKC Suffix", "Rally Trial", "RE", "AKC Rally Excellent",
	"AKC Suffix", "Rally Trial", "RAE", "AKC Rally Advanced Excellent",
	"AKC Suffix", "Rally Trial", "RI", "AKC Rally Intermediate",
	"AKC Suffix", "Rally Trial", "RM", "AKC Rally Master",
	"AKC Suffix", "Scentwork Trial", "SBA", "Scent Work Buried Advanced",
	"AKC Suffix", "Scentwork Trial", "SBAE", "Scent Work Buried Advanced Elite",
	"AKC Suffix", "Scentwork Trial", "SBE", "Scent Work Buried Excellent",
	"AKC Suffix", "Scentwork Trial", "SBEE", "Scent Work Buried Excellent Elite",
	"AKC Suffix", "Scentwork Trial", "SBM", "Scent Work Buried Master",
	"AKC Suffix", "Scentwork Trial", "SBME", "Scent Work Buried Master Elite",
	"AKC Suffix", "Scentwork Trial", "SBN", "Scent Work Buried Novice",
	"AKC Suffix", "Scentwork Trial", "SBNE", "Scent Work Buried Novice Elite",
	"AKC Suffix", "Lure Coursing", "SC", "Senior Courser",
	"AKC Suffix", "Scentwork Trial", "SCA", "Scent Work Container Advanced",
	"AKC Suffix", "Scentwork Trial", "SCAE", "Scent Work Container Advanced Elite",
	"AKC Suffix", "Scentwork Trial", "SCE", "Scent Work Container Excellent",
	"AKC Suffix", "Scentwork Trial", "SCEE", "Scent Work Container Excellent Elite",
	"AKC Suffix", "Scentwork Trial", "SCM", "Scent Work Container Master",
	"AKC Suffix", "Scentwork Trial", "SCME", "Scent Work Cotnainer Master Elite",
	"AKC Suffix", "Scentwork Trial", "SCN", "Scent Work Container Novice",
	"AKC Suffix", "Scentwork Trial", "SCNE", "Scent Work Container Novice Elite",
	"AKC Suffix", "Earthdog", "SE", "Senior Earthdog",
	"AKC Suffix", "Scentwork Trial", "SEA", "Scent Work Exterior Advanced",
	"AKC Suffix", "Scentwork Trial", "SEAE", "Scent Work Exterior Advanced Elite",
	"AKC Suffix", "Scentwork Trial", "SEE", "Scent Work Exterior Excellent",
	"AKC Suffix", "Scentwork Trial", "SEEE", "Scent Work Exterior Excellent Elite",
	"AKC Suffix", "Scentwork Trial", "SEM", "Scent Work Exterior Master",
	"AKC Suffix", "Scentwork Trial", "SEME", "Scent Work Exterior Master Elite",
	"AKC Suffix", "Scentwork Trial", "SEN", "Scent Work Exterior Novice",
	"AKC Suffix", "Scentwork Trial", "SENE", "Scent Work Exterior Novice Elite",
	"AKC Suffix", "Hunting Test", "SH", "Senior Hunter",
	"AKC Suffix", "Scentwork Trial", "SHA", "Senior Hunter Advanced",
	"AKC Suffix", "Scentwork Trial", "SHDA", "Scent Work Handler Discrimination Advanced",
	"AKC Suffix", "Scentwork Trial", "SHDAE", "Scent Work Handler Discrimination Advanced Elite",
	"AKC Suffix", "Scentwork Trial", "SHDE", "Scent Work Handler Discrimination Excellent",
	"AKC Suffix", "Scentwork Trial", "SHDEE", "Scent Work Handler Discrimination Excellent Elite",
	"AKC Suffix", "Scentwork Trial", "SHDM", "Scent Work Handler Discrimination Master",
	"AKC Suffix", "Scentwork Trial", "SHDME", "Scent Work Handler Discrimination Master Elite",
	"AKC Suffix", "Scentwork Trial", "SHDN", "Scent Work Handler Discrimination Novice",
	"AKC Suffix", "Scentwork Trial", "SHDNE", "Scent Work Handler Discrimination Novice Elite",
	"AKC Suffix", "Hunting Test", "SHR", "Senior Hunter Retriever",
	"AKC Suffix", "Hunting Test", "SHU", "Senior Hunter Upland",
	"AKC Suffix", "Scentwork Trial", "SIA", "Scent Work Interior Advanced",
	"AKC Suffix", "Scentwork Trial", "SIAE", "Scent Work Interior Advanced Elite",
	"AKC Suffix", "Scentwork Trial", "SIE", "Scent Work Interior Excellent",
	"AKC Suffix", "Scentwork Trial", "SIEE", "Scent Work Interior Excellent Elite",
	"AKC Suffix", "Scentwork Trial", "SIM", "Scent Work Interior Master",
	"AKC Suffix", "Scentwork Trial", "SIME", "Scent Work Interior Master Elite",
	"AKC Suffix", "Scentwork Trial", "SIN", "Scent Work Interior Novice",
	"AKC Suffix", "Scentwork Trial", "SINE", "Scent Work Interior Novice Elite",
	"AKC Suffix", "Scentwork Trial", "SWA", "Scent Work Advanced",
	"AKC Suffix", "Scentwork Trial", "SWAE", "Scent Work Advanced Elite",
	"AKC Suffix", "Scentwork Trial", "SWD", "Scent Work Detective",
	"AKC Suffix", "Scentwork Trial", "SWE", "Scent Work Excellent",
	"AKC Suffix", "Scentwork Trial", "SWEE", "Scent Work Excellent Elite",
	"AKC Suffix", "Scentwork Trial", "SWM", "Scent Work Master",
	"AKC Suffix", "Scentwork Trial", "SWME", "Scent Work Master Elite",
	"AKC Suffix", "Scentwork Trial", "SWN", "Scent Work Novice",
	"AKC Suffix", "Scentwork Trial", "SWNE", "Scent Work Novice Elite",
	"AKC Suffix", "Agility Trial", "T2B", "Time 2 Beat",
	"AKC Suffix", "Agility Trial", "T2BP", "Time 2 Beat Preferred",
	"AKC Suffix", "Tracking Test", "TD", "Tracking Dog",
	"AKC Suffix", "Tracking Test", "TDU", "Tracking Dog Urban",
	"AKC Suffix", "Tracking Test", "TDX", "Tracking Dog Excellent",
	"AKC Suffix", "Therapy Dog", "THD", "Therapy Dog Title",
	"AKC Suffix", "Therapy Dog", "THDA", "Therapy Dog Advanced",
	"AKC Suffix", "Therapy Dog", "THDD", "Distinguished Therapy Dog",
	"AKC Suffix", "Therapy Dog", "THDN", "Therapy Dog Novice",
	"AKC Suffix", "Therapy Dog", "THDX", "Therapy Dog Excellent",
	"AKC Suffix", "Trick Dog", "TKN", "Novice Trick Dog",
	"AKC Suffix", "Trick Dog", "TKI", "Intermediate Trick Dog",
	"AKC Suffix", "Trick Dog", "TKA", "Advanced Trick Dog",
	"AKC Suffix", "Trick Dog", "TKP", "Trick Dog Performer",
	"AKC Suffix", "Trick Dog", "TKE", "Trick Dog Elite Performer",
	"AKC Suffix", "Agility Trial", "TQX", "Triple Q Excellent",
	"AKC Suffix", "Agility Trial", "TQXP", "Triple Q Excellent Preferred",
	"AKC Suffix", "Obedience Trial", "UD", "Utility Dog",
	"AKC Suffix", "Obedience Trial", "UDX", "Utility Dog Excellent",
	"AKC Suffix", "Obedience Trial AND Agility Trial AND Tracking Test", "VCD1", "Versatile Companion Dog 1",
	"AKC Suffix", "Obedience Trial AND Agility Trial AND Tracking Test", "VCD2", "Versatile Companion Dog 2",
	"AKC Suffix", "Obedience Trial AND Agility Trial AND Tracking Test", "VCD3", "Versatile Companion Dog 3",
	"AKC Suffix", "Obedience Trial AND Agility Trial AND Tracking Test", "VCD4", "Versatile Companion Dog 4",
	"AKC Suffix", "Obedience Trial", "VER", "Versatility",
	"AKC Suffix", "Tracking Test", "VST", "Variable Surface Tracking",
	"AKC Suffix", "Agility Trial", "XF", "Excellent FAST",
	"AKC Suffix", "Agility Trial", "XFP", "Excellent FAST Preferred",
	"AKC Airedale Terrier Club of America", "Fur Tracking", "JFT", "Junior Fur Tracker",
	"AKC Airedale Terrier Club of America", "Fur Tracking", "SFT", "Senior Fur Tracker",
	"AKC Airedale Terrier Club of America", "Fur Tracking", "MFT", "Master Fur Tracker",
	"AKC American Bloodhound Club", "Man Trailer", "MT", "Man Trailer",
	"AKC American Bloodhound Club", "Man Trailer", "MTI", "Man Trailer Intermediate",
	"AKC American Bloodhound Club", "Man Trailer", "MTX", "Man Trailer Excellent",
	"AKC Basset Hound Club of America", "Hunting", "HH", "Hunting Hound",
	"AKC Basset Hound Club of America", "Hunting", "SHH", "Senior Hunting Hound",
	"AKC Basset Hound Club of America", "Hunting", "MHH", "Master Hunting Hound",
	"AKC Basset Hound Club of America", "Hunting", "MHE", "Master Hunting Excellent",
	"AKC Dachshund Club of America", "Hunting", "HH", "Hunting Hound",
	"AKC Dachshund Club of America", "Hunting", "SHH", "Senior Hunting Hound",
	"AKC Dachshund Club of America", "Hunting", "MHH", "Master Hunting Hound",
	"AKC Dachshund Club of America", "Hunting", "MHE", "Master Hunting Excellent",
	"AKC Dalmatian Club of America", "Coaching", "CC", "Coaching Certificate",
	"AKC Dalmatian Club of America", "Road Dog", "RD", "Road Dog",
	"AKC Dalmatian Club of America", "Road Dog", "RDX", "Road Dog Excellent",
	"AKC Doberman Pinscher Club of America", "Working Aptitude", "WAC", "Working Aptitude Certificate",
	"AKC Golden Retriever Club of America", "Conformation", "CCA", "Certificate of Conformation Assessment",
	"AKC Nova Scotia Duck Tolling Retriever Club", "Working Certificate", "WC", "Working Certificate",
	"AKC Nova Scotia Duck Tolling Retriever Club", "Working Certificate", "WCI", "Working Certificate Intermediate",
	"AKC Nova Scotia Duck Tolling Retriever Club", "Working Certificate", "WCX", "Working Certificate Excellent",
	"AKC Petit Basset Griffon Vendeen", "Hunting", "PCJH", "Parent Club Junior Hunter",
	"AKC Petit Basset Griffon Vendeen", "Hunting", "PCSH", "Parent Club Senior Hunter",
	"AKC Petit Basset Griffon Vendeen", "Hunting", "PCMH", "Parent Club Master Hunter",
	"AKC Petit Basset Griffon Vendeen", "Hunting", "HH", "Hunting Hound",
	"AKC Petit Basset Griffon Vendeen", "Hunting", "SHH", "Senior Hunting Hound",
	"AKC Petit Basset Griffon Vendeen", "Hunting", "MHH", "Master Hunting Hound",
	"AKC Petit Basset Griffon Vendeen", "Hunting", "MHE", "Master Hunting Excellent",
	"AKC Siberian Husky Club of America", "Sledding", "SD", "Sled Dog",
	"AKC Siberian Husky Club of America", "Sledding", "SDX", "Sled Dog Excellent",
	"AKC Siberian Husky Club of America", "Sledding", "SDO", "Sled Dog Outstanding",
	"AKC West Highland White Terrier Club of America", "Conformation", "CCA", "Certificate of Conformation Assessment",
	"AKC American Rottweiler Club", "Carting", "CS", "Carting Started",
	"AKC American Rottweiler Club", "Carting", "CI", "Carting Intermediate",
	"AKC American Rottweiler Club", "Carting", "CX", "Carting Excellent",
	"AKC American Rottweiler Club", "Carting", "CST", "Carting Started Team",
	"AKC American Rottweiler Club", "Carting", "CIT", "Carting Intermediate Team",
	"AKC American Rottweiler Club", "Carting", "CXT", "Carting Excellent Team",
	"AKC American Bouvier des Flandres Club", "Drafting", "NDD", "Novice Draft Dog",
	"AKC Bernese Mountain Dog Club of America", "Drafting", "NDD", "Novice Draft Dog",
	"AKC Belgian Sheepdog Club of America", "Drafting", "NDD", "Novice Draft Dog",
	"AKC Briard Club of America", "Drafting", "", "NDD", "Novice Draft Dog",
	"AKC Greater Swiss Mountain Dog Club of America", "Drafting", "NDD", "Novice Draft Dog",
	"AKC Mastiff Club of America", "Drafting", "NDD", "Novice Draft Dog",
	"AKC Leonberger Club of America", "Drafting", "NDD", "Novice Draft Dog",
	"AKC American Bouvier des Flandres Club", "Drafting", "DD", "Draft Dog",
	"AKC Bernese Mountain Dog Club of America", "Drafting", "DD", "Draft Dog",
	"AKC Belgian Sheepdog Club of America", "Drafting", "DD", "Draft Dog",
	"AKC Briard Club of America", "Drafting", "DD", "Draft Dog",
	"AKC Greater Swiss Mountain Dog Club of America", "Drafting", "DD", "Draft Dog",
	"AKC Mastiff Club of America", "Drafting", "DD", "Draft Dog",
	"AKC Leonberger Club of America", "Drafting", "DD", "Draft Dog",
	"AKC American Bouvier des Flandres Club", "Drafting", "NBDD", "Novice Brace Draft Dog",
	"AKC Bernese Mountain Dog Club of America", "Drafting", "NBDD", "Novice Brace Draft Dog",
	"AKC Belgian Sheepdog Club of America", "Drafting", "NBDD", "Novice Brace Draft Dog",
	"AKC Briard Club of America", "Drafting", "NBDD", "Novice Brace Draft Dog",
	"AKC Greater Swiss Mountain Dog Club of America", "Drafting", "NBDD", "Novice Brace Draft Dog",
	"AKC Mastiff Club of America", "Drafting", "NBDD", "Novice Brace Draft Dog",
	"AKC Leonberger Club of America", "Drafting", "NBDD", "Novice Brace Draft Dog",
	"AKC American Bouvier des Flandres Club", "Drafting", "BDD", "Brace Draft Dog",
	"AKC Bernese Mountain Dog Club of America", "Drafting", "BDD", "Brace Draft Dog",
	"AKC Belgian Sheepdog Club of America", "Drafting", "BDD", "Brace Draft Dog",
	"AKC Briard Club of America", "Drafting", "BDD", "Brace Draft Dog",
	"AKC Greater Swiss Mountain Dog Club of America", "Drafting", "BDD", "Brace Draft Dog",
	"AKC Mastiff Club of America", "Drafting", "BDD", "Brace Draft Dog",
	"AKC Leonberger Club of America", "Drafting", "BDD", "Brace Draft Dog",
	"AKC St. Bernard Club of America", "Drafting", "DD", "Draft Dog",
	"AKC St. Bernard Club of America", "Drafting", "TDD", "Team Draft Dog",
	"AKC Leonberger Club of America", "Drafting", "TDD", "Team Draft Dog",
	"AKC Working Dog", "Obedience", "BH", "Basic Companion Dog",
	"AKC Working Dog", "Tracking", "FH1", "Advanced Tracking",
	"AKC Working Dog", "Tracking", "FH2", "Superior Tracking",
	"AKC Working Dog", "Schutzhund", "IPO1", "International Novice Schutzhund",
	"AKC Working Dog", "Schutzhund", "IPO2", "International Intermediate Schutzhund",
	"AKC Working Dog", "Schutzhund", "IPO3", "International Master Level Schutzhund",
	"AKC Working Dog", "Schutzhund", "SCHH1", "Novice Schutzhund",
	"AKC Working Dog", "Schutzhund", "SCHH2", "Intermediate Schutzhund",
	"AKC Working Dog", "Schutzhund", "SCHH3", "Master Level Schutzhund",
	"AKC Working Dog", "Schutzhund", "SCHHA", "Novice Schutzhund A",
	"AKC Working Dog", "Temperament Test", "TC", "Temperament Certification",
	"AKC Working Dog", "Temperament Test", "TT", "Temperament Test",
	"AKC Working Dog", "Working Dog", "WDS1", "Working Dog Sport 1",
	"AKC Working Dog", "Working Dog", "WDS2", "Working Dog Sport 2",
	"AKC Working Dog", "Working Dog", "WDS3", "Working Dog Sport 3",
	"AKC North American Flyball Association (NAFA)", "Flyball", "FDCh", "Flyball Dog Champion",
	"AKC North American Flyball Association (NAFA)", "Flyball", "FM", "Flyball Master",
	"AKC North American Flyball Association (NAFA)", "Flyball", "ONYX", "ONYX",
	"AKC Barn Hunt Association", "Barn Hunt", "CZ8B", "Crazy 8s Bronze",
	"AKC Barn Hunt Association", "Barn Hunt", "CZ8S", "Crazy 8s Silver",
	"AKC Barn Hunt Association", "Barn Hunt", "CZ8G", "Crazy 8s Gold",
	"AKC Barn Hunt Association", "Barn Hunt", "CZ8P", "Crazy 8s Platinum",
	"AKC Barn Hunt Association", "Barn Hunt", "RATN", "Novice Barn Hunt",
	"AKC Barn Hunt Association", "Barn Hunt", "RATO", "Open Barn Hunt",
	"AKC Barn Hunt Association", "Barn Hunt", "RATS", "Senior Barn Hunt",
	"AKC Barn Hunt Association", "Barn Hunt", "RATM", "Master Barn Hunt",
	"AKC Barn Hunt Association", "Barn Hunt", "RATCh", "Barn Hunt Champion",
	"AKC Barn Hunt Association", "Barn Hunt", "RATChX", "Barn Hunt Master Champion",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DN", "Dock Novice",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DJ", "Dock Junior",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DS", "Dock Senior",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DM", "Dock Master",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DE", "Dock Elite",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DNA", "Dock Novice Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DJA", "Dock Junior Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DSA", "Dock Senior Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DMA", "Dock Master Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DEA", "Dock Elite Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DNX", "Dock Novice Excellent",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DJX", "Dock Junior Excellent",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DSX", "Dock Senior Excellent",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DMX", "Dock Master Excellent",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "DEX", "Dock Elite Excellent",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AN", "Air Retrieve Novice",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AJ", "Air Retrieve Junior",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AS", "Air Retrieve Senior",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AM", "Air Retrieve Master",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AE", "Air Retrieve Elite",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "ANA", "Air Retrieve Novice Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AJA", "Air Retrieve Junior Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "ASA", "Air Retrieve Senior Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AMA", "Air Retrieve Master Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AEA", "Air Retrieve Elite Advanced",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "ANX", "Air Retrieve Novice Excellent",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AJX", "Air Retrieve Junior Excellent",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "ASX", "Air Retrieve Senior Excellent",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AMX", "Air Retrieve Master Excellent",
	"AKC North America Diving Dogs (NADD)", "Dock Diving", "AEX", "Air Retrieve Elite Excellent",
	"AKC UpDog Challenge", "Disc Dog", "DDB", "Disc Dog Bronze",
	"AKC UpDog Challenge", "Disc Dog", "DDBE", "Disc Dog Bronze Elite",
	"AKC UpDog Challenge", "Disc Dog", "DDG", "Disc Dog Gold",
	"AKC UpDog Challenge", "Disc Dog", "DDGE", "Disc Dog Gold Elite",
	"AKC UpDog Challenge", "Disc Dog", "DDP", "Disc Dog Platinum",
	"AKC UpDog Challenge", "Disc Dog", "DDPE", "Disc Dog Platinum Elite",
	"AKC UpDog Challenge", "Disc Dog", "DDS", "Disc Dog Silver",
	"AKC UpDog Challenge", "Disc Dog", "DDSE", "Disc Dog Silver Elite",
	"AKC UpDog Challenge", "Disc Dog", "DDU", "Disc Dog Unobtanium",
	"AKC UpDog Challenge", "Disc Dog", "DDUE", "Disc Dog Unobtanium Elite",
	"DMWYD Suffix", "Trick Dog", "NTD", "Novice Trick Dog",
	"DMWYD Suffix", "Trick Dog", "ITD", "Intermediate Trick Dog",
	"DMWYD Suffix", "Trick Dog", "ATD", "Advanced Trick Dog",
	"DMWYD Suffix", "Trick Dog", "ETD", "Expert Trick Dog",
	"DMWYD Suffix", "Trick Dog", "NTD-M", "Novice Masters Trick Dog",
	"DMWYD Suffix", "Trick Dog", "ITD-M", "Intermediate Masters Trick Dog",
	"DMWYD Suffix", "Trick Dog", "ATD-M", "Advanced Masters Trick Dog",
	"DMWYD Suffix", "Trick Dog", "ETD-M", "Expert Masters Trick Dog",
	"DMWYD Prefix", "Trick Dog", "TDCH", "Trick Dog Champion",
	"DMWYD Prefix", "Trick Dog", "TDGCH", "Trick Dog Grand Champion",
	"DMWYD Suffix", "Stunt Dog", "NSD", "Novice Stunt Dog",
	"DMWYD Suffix", "Stunt Dog", "OSD", "Open Stunt Dog",
	"DMWYD Suffix", "Stunt Dog", "PSD", "Proven Stunt Dog",
	"DMWYD Suffix", "Stunt Dog", "SDPro", "Stunt Dog Professional",
	"DMWYD Prefix", "Stunt Dog", "SDCH", "Stunt Dog Champion",
	"DMWYD Prefix", "Stunt Dog", "SDGCH", "Stunt Dog Grand Champion",
	"DMWYD Prefix", "Stunt Dog", "SDGCH2", "Stunt Dog Grand Champion 2",
	"DMWYD Prefix", "Stunt Dog", "SDGCH3", "Stunt Dog Grand Champion 3",
	"DMWYD Suffix", "Canine Fitness", "CCF1", "Canine Conditioning Fitness Level 1",
	"DMWYD Suffix", "Canine Fitness", "CCF2", "Canine Conditioning Fitness Level 2",
	"DMWYD Suffix", "Canine Fitness", "CCF3", "Canine Conditioning Fitness Level 3",
	"DMWYD Suffix", "Canine Fitness", "CCF4", "Canine Conditioning Fitness Level 4",
	"DMWYD Prefix", "Canine Fitness", "CCF-CH", "Canine Conditioning Fitness Champion",
	"DMWYD Suffix", "Trick Dog AND Stunt Dog AND Canine Fitness", "TC1", "Triple Crown Level 1 (Trick Dog Novice, Novice Stunt Dog, Canine Conditioning Level 1)",
	"DMWYD Suffix", "Trick Dog AND Stunt Dog AND Canine Fitness", "TC2", "Triple Crown Level 2 (Trick Dog Intermediate, Open Stunt Dog, Canine Conditioning Level 2)",
	"DMWYD Suffix", "Trick Dog AND Stunt Dog AND Canine Fitness", "TC3", "Triple Crown Level 3 (Trick Dog Advanced, Proven Stunt Dog, Canine Conditioning Level 3)",
	"DMWYD Suffix", "Trick Dog AND Stunt Dog AND Canine Fitness", "TC4", "Triple Crown Level 4 (Trick Dog Expert, Stunt Dog Professional, Canine Conditioning Level 4)",
	"DMWYD Prefix", "Trick Dog AND Stunt Dog AND Canine Fitness", "TCCH", "Triple Crown Champion (Trick Dog Champion, Stunt Dog Champion, Canine Conditioning Champion)",
	"DMWYD Suffix", "DMWYD Specialty", "A+", "Teacher's Pet",
	"DMWYD Suffix", "DMWYD Specialty", "BTC24", "Beat The Clock 24 Seconds",
	"DMWYD Suffix", "DMWYD Specialty", "BTC48", "Beat The Clock 48 Seconds",
	"DMWYD Suffix", "DMWYD Specialty", "BTC60", "Beat The Clock 60 Seconds",
	"DMWYD Suffix", "DMWYD Specialty", "AKA", "That's My Name",
	"DMWYD Suffix", "DMWYD Specialty", "AtoZ", "Alphabet Tricks",
	"DMWYD Suffix", "DMWYD Specialty", "20:1", "20 Dog Tricks: One Prop",
	"DMWYD Suffix", "DMWYD Specialty", "SOR", "Summer of Ruff",
	"DMWYD Suffix", "DMWYD Specialty", "SSH", "Summer Scavenger Hunt",
	"DMWYD Suffix", "Canine Fitness", "2K9", "2K-9 RUff Run",
	"DMWYD Suffix", "Canine Fitness", "T3", "Triple Threat",
	"DMWYD Suffix", "Animal Actor", "AA1", "Animal Actor Level 1 - Photoshot",
	"DMWYD Suffix", "Animal Actor", "AA2", "Animal Actor Level 2 - Actor",
	"DMWYD Suffix", "Animal Actor", "AA3", "Animal Actor Level 3 - Film",
	"DMWYD Suffix", "Animal Actor", "AA4", "Animal Actor Level 4 - Leading Role",
	"DMWYD Suffix", "Animal Actor", "AA5", "Animal Actor Level 5 - Professional",
	"ASCA Prefix", "Conformation", "CH", "Champion",
	"ASCA Prefix", "Conformation", "A-CH", "Altered Champion",
	"ASCA Suffix", "Tracking", "TD", "Tracking Dog",
	"ASCA Suffix", "Tracking", "TDX", "Tracking Dog Excellent",
	"ASCA Suffix", "Tracking", "TDU", "Tracking Dog Urban",
	"ASCA Suffix", "Obedience", "BN", "Beginner Novice",
	"ASCA Suffix", "Obedience", "GN", "Grad Novice",
	"ASCA Suffix", "Obedience", "CD", "Companion Dog",
	"ASCA Suffix", "Obedience", "CDX", "", "Companion Dog Excellent",
	"ASCA Suffix", "Obedience", "ODX", "", "Open Dog Excellent",
	"ASCA Suffix", "Obedience", "UD", "Utility Dog",
	"ASCA Suffix", "Obedience", "UDX", "", "Utility Dog Excellent (CDX Branch)",
	"ASCA Suffix", "Obedience", "UDX-O", "Utility Dog Excellent (ODX Branch)",
	"ASCA Suffix", "Obedience", "UDX-V", "Utility Dog Excellent Veterans",
	"ASCA Prefix", "Obedience", "OTCH", "Obedience Champion (CDX Branch)",
	"ASCA Prefix", "Obedience", "OTCH2", "Obedience Champion (CDX Branch) 2",
	"ASCA Prefix", "Obedience", "OTCH3", "Obedience Champion (CDX Branch) 3",
	"ASCA Prefix", "Obedience", "OTCH4", "Obedience Champion (CDX Branch) 4",
	"ASCA Prefix", "Obedience", "OTCH5", "Obedience Champion (CDX Branch) 5",
	"ASCA Prefix", "Obedience", "OTCH-O", "Obedience Champion (ODX Branch)",
	"ASCA Prefix", "Obedience", "OTCH-O2", "Obedience Champion (ODX Branch) 2",
	"ASCA Prefix", "Obedience", "OTCH-O3", "Obedience Champion (ODX Branch) 3",
	"ASCA Prefix", "Obedience", "OTCH-O4", "Obedience Champion (ODX Branch) 4",
	"ASCA Prefix", "Obedience", "OTCH-O5", "Obedience Champion (ODX Branch) 5",
	"ASCA Suffix", "Rally", "RN", "Rally Novice",
	"ASCA Suffix", "Rally", "RNX", "Rally Novice X",
	"ASCA Suffix", "Rally", "RNC", "Rally Novice C (Class)",
	"ASCA Suffix", "Rally", "RA", "Rally Advanced",
	"ASCA Suffix", "Rally", "RAX", "Rally Advanced X",
	"ASCA Suffix", "Rally", "RAC", "Rally Advanced C (Class)",
	"ASCA Suffix", "Rally", "RE", "Rally Excellent",
	"ASCA Suffix", "Rally", "REX", "Rally Excellent X",
	"ASCA Suffix", "Rally", "REC", "Rally Excellent C (Class)",
	"ASCA Suffix", "Rally", "RM", "Rally Master",
	"ASCA Suffix", "Rally", "RMX", "Rally Master X",
	"ASCA Suffix", "Rally", "RMC", "Rally Master C (Class)",
	"ASCA Suffix", "Rally", "REM", "Rally Excellent Masters",
	"ASCA Suffix", "Rally", "REMX", "Rally Excellent Masters X",
	"ASCA Suffix", "Rally", "RTX", "Rally Trial X",
	"ASCA Suffix", "Rally", "RTC", "Rally Trial C (Class)",
	"ASCA Prefix", "Rally", "RTCH", "Rally Trial Champion",
	"ASCA Prefix", "Rally", "RTCH2", "Rally Trial Champion 2",
	"ASCA Prefix", "Rally", "RTCH3", "Rally Trial Champion 3",
	"ASCA Prefix", "Rally", "RTCH4", "Rally Trial Champion 4",
	"ASCA Prefix", "Rally", "RTCH5", "Rally Trial Champion 5",
	"ASCA Suffix", "Herding", "STDd", "Started Ducks",
	"ASCA Suffix", "Herding", "STDc", "Started Cattle",
	"ASCA Suffix", "Herding", "STDs", "Started Sheep",
	"ASCA Suffix", "Herding", "STDdc", "Started Ducks & Cattle",
	"ASCA Suffix", "Herding", "STDds", "Started Ducks & Sheep",
	"ASCA Suffix", "Herding", "STDcs", "Started Cattle & Sheep",
	"ASCA Suffix", "Herding", "STDdcs", "Started Ducks, Cattle & Sheep",
	"ASCA Suffix", "Herding", "OTDd", "Open Ducks",
	"ASCA Suffix", "Herding", "OTDc", "Open Cattle",
	"ASCA Suffix", "Herding", "OTDs", "Open Sheep",
	"ASCA Suffix", "Herding", "OTDdc", "Open Ducks & Cattle",
	"ASCA Suffix", "Herding", "OTDds", "Open Ducks & Sheep",
	"ASCA Suffix", "Herding", "OTDcs", "Open Cattle & Sheep",
	"ASCA Suffix", "Herding", "OTDdcs", "Open Ducks, Cattle & Sheep",
	"ASCA Suffix", "Herding", "ATDd", "Advanced Ducks",
	"ASCA Suffix", "Herding", "ATDc", "Advanced Cattle",
	"ASCA Suffix", "Herding", "ATDs", "Advanced Sheep",
	"ASCA Suffix", "Herding", "ATDdc", "Advanced Ducks & Cattle",
	"ASCA Suffix", "Herding", "ATDds", "Advanced Ducks & Sheep",
	"ASCA Suffix", "Herding", "ATDcs", "Advanced Cattle & Sheep",
	"ASCA Suffix", "Herding", "ATDdcs", "Advanced Ducks, Cattle & Sheep",
	"ASCA Suffix", "Herding", "ATD-Md", "Advanced Trial Dog Multiple Courses Ducks",
	"ASCA Suffix", "Herding", "ATD-Mc", "Advanced Trial Dog Multiple Courses Cattle",
	"ASCA Suffix", "Herding", "ATD-Ms", "Advanced Trial Dog Multiple Courses Sheep",
	"ASCA Suffix", "Herding", "ATD-Mdc", "Advanced Trial Dog Multiple Courses Ducks & Cattle",
	"ASCA Suffix", "Herding", "ATD-Mds", "Advanced Trial Dog Multiple Courses Ducks & Sheep",
	"ASCA Suffix", "Herding", "ATD-Mcs", "Advanced Trial Dog Multiple Courses Cattle & Sheep",
	"ASCA Suffix", "Herding", "ATD-Mdcs", "Advanced Trial Dog Multiple Courses Ducks, Cattle, & Sheep",
	"ASCA Suffix", "Herding", "ATD-Xd", "Advanced Trial Dog Excellent Ducks",
	"ASCA Suffix", "Herding", "ATD-Xc", "Advanced Trial Dog Excellent Cattle",
	"ASCA Suffix", "Herding", "ATD-Xs", "Advanced Trial Dog Excellent Sheep",
	"ASCA Suffix", "Herding", "ATD-Xdc", "Advanced Trial Dog Excellent Ducks & Cattle",
	"ASCA Suffix", "Herding", "ATD-Xds", "Advanced Trial Dog Excellent Ducks & Sheep",
	"ASCA Suffix", "Herding", "ATD-Xcs", "Advanced Trial Dog Excellent Cattle & Sheep",
	"ASCA Suffix", "Herding", "ATD-Xdcs", "Advanced Trial Dog Excellent Ducks, Cattle, & Sheep",
	"ASCA Suffix", "Herding", "PATDd", "Post Advanced Trial Dog Ducks",
	"ASCA Suffix", "Herding", "PATDc", "Post Advanced Trial Dog Cattle",
	"ASCA Suffix", "Herding", "PATDs", "Post Advanced Trial Dog Sheep",
	"ASCA Suffix", "Herding", "PATDdc", "Post Advanced Trial Dog Ducks & Cattle",
	"ASCA Suffix", "Herding", "PATDds", "Post Advanced Trial Dog Ducks & Sheep",
	"ASCA Suffix", "Herding", "PATDcs", "Post Advanced Trial Dog Cattle & Sheep",
	"ASCA Suffix", "Herding", "PATDdcs", "Post Advanced Trial Dog Ducks, Cattle & Sheep",
	"ASCA Suffix", "Herding", "RD", "Ranch Dog",
	"ASCA Suffix", "Herding", "RTDd", "Ranch Trial Dog Ducks",
	"ASCA Suffix", "Herding", "RTDc", "Ranch Trial Dog Cattle",
	"ASCA Suffix", "Herding", "RTDs", "Ranch Trial Dog Sheep",
	"ASCA Suffix", "Herding", "RTDdc", "Ranch Trial Dog Ducks & Cattle",
	"ASCA Suffix", "Herding", "RTDds", "Ranch Trial Dog Ducks & Sheep",
	"ASCA Suffix", "Herding", "RTDcs", "Ranch Trial Dog Cattle & Sheep",
	"ASCA Suffix", "Herding", "RTDdcs", "Ranch Trial Dog Ducks, Cattle & Sheep",
	"ASCA Suffix", "Herding", "OFTDd", "Open Farm Trial Dog Ducks",
	"ASCA Suffix", "Herding", "OFTDc", "Open Farm Trial Dog Cattle",
	"ASCA Suffix", "Herding", "OFTDs", "Open Farm Trial Dog Sheep",
	"ASCA Suffix", "Herding", "OFTDdc", "Open Farm Trial Dog Ducks & Cattle",
	"ASCA Suffix", "Herding", "OFTDds", "Open Farm Trial Dog Ducks & Sheep",
	"ASCA Suffix", "Herding", "OFTDcs", "Open Farm Trial Dog Cattle & Sheep",
	"ASCA Suffix", "Herding", "OFTDdcs", "Open Farm Trial Dog Ducks, Cattle & Sheep",
	"ASCA Suffix", "Herding", "AFTDd", "Advanced Farm Trial Dog Ducks",
	"ASCA Suffix", "Herding", "AFTDc", "Advanced Farm Trial Dog Cattle",
	"ASCA Suffix", "Herding", "AFTDs", "Advanced Farm Trial Dog Sheep",
	"ASCA Suffix", "Herding", "AFTDdc", "Advanced Farm Trial Dog Ducks & Cattle",
	"ASCA Suffix", "Herding", "AFTDds", "Advanced Farm Trial Dog Ducks & Sheep",
	"ASCA Suffix", "Herding", "AFTDcs", "Advanced Farm Trial Dog Cattle & Sheep",
	"ASCA Suffix", "Herding", "AFTDdcs", "Advanced Farm Trial Dog Ducks, Cattle & Sheep",
	"ASCA Suffix", "Herding", "AFTD-Xd", "Advanced Farm Trial Dog - X Ducks",
	"ASCA Suffix", "Herding", "AFTD-Xc", "Advanced Farm Trial Dog - X Cattle",
	"ASCA Suffix", "Herding", "AFTD-Xs", "Advanced Farm Trial Dog - X Sheep",
	"ASCA Suffix", "Herding", "AFTD-Xdc", "Advanced Farm Trial Dog - X Ducks & Cattle",
	"ASCA Suffix", "Herding", "AFTD-Xds", "Advanced Farm Trial Dog - X Ducks & Sheep",
	"ASCA Suffix", "Herding", "AFTD-Xcs", "Advanced Farm Trial Dog - X Cattle & Sheep",
	"ASCA Suffix", "Herding", "AFTD-Xdcs", "Advanced Farm Trial Dog - X Ducks, Cattle & Sheep",
	"ASCA Prefix", "Herding", "FTCH", "Farm Trial Champion",
	"ASCA Prefix", "Herding", "WTCH", "Working Trial Champion",
	"ASCA Prefix", "Herding", "WTCH-M", "Working Trial Champion Multiple Courses",
	"ASCA Prefix", "Herding", "WTCH-X", "Working Trial Champion Excellent",
	"ASCA Prefix", "Herding", "SDCH", "Stockdog Champion",
	"ASCA Suffix", "Agility", "RS-N", "Regular Standard Novice",
	"ASCA Suffix", "Agility", "RS-O", "Regular Standard Open",
	"ASCA Suffix", "Agility", "RS-E", "Regular Standard Elite",
	"ASCA Suffix", "Agility", "RV-N", "Regular Veteran Novice",
	"ASCA Suffix", "Agility", "RV-O", "Regular Veteran Open",
	"ASCA Suffix", "Agility", "RV-E", "Regular Veteran Elite",
	"ASCA Suffix", "Agility", "RJ-N", "Regular Junior Novice",
	"ASCA Suffix", "Agility", "RJ-O", "Regular Junior Open",
	"ASCA Suffix", "Agility", "RJ-E", "Regular Junior Elite",
	"ASCA Suffix", "Agility", "JS-N", "Jumpers Standard Novice",
	"ASCA Suffix", "Agility", "JS-O", "Jumpers Standard Open",
	"ASCA Suffix", "Agility", "JS-E", "Jumpers Standard Elite",
	"ASCA Suffix", "Agility", "JV-N", "Jumpers Veteran Novice",
	"ASCA Suffix", "Agility", "JV-O", "Jumpers Veteran Open",
	"ASCA Suffix", "Agility", "JV-E", "Jumpers Veteran Elite",
	"ASCA Suffix", "Agility", "JJ-N", "Jumpers Junior Novice",
	"ASCA Suffix", "Agility", "JJ-O", "Jumpers Junior Open",
	"ASCA Suffix", "Agility", "JJ-E", "Jumpers Junior Elite",
	"ASCA Suffix", "Agility", "GS-N", "Gamblers Standard Novice",
	"ASCA Suffix", "Agility", "GS-O", "Gamblers Standard Open",
	"ASCA Suffix", "Agility", "GS-E", "Gamblers Standard Elite",
	"ASCA Suffix", "Agility", "GV-N", "Gamblers Veteran Novice",
	"ASCA Suffix", "Agility", "GV-O", "Gamblers Veteran Open",
	"ASCA Suffix", "Agility", "GV-E", "Gamblers Veteran Elite",
	"ASCA Suffix", "Agility", "GJ-N", "Gamblers Junior Novice",
	"ASCA Suffix", "Agility", "GJ-O", "Gamblers Junior Open",
	"ASCA Suffix", "Agility", "GJ-E", "Gamblers Junior Elite",
	"ASCA Suffix", "Agility", "RS-N-OP", "Regular Standard Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "RS-O-OP", "Regular Standard Open Outstanding Performance",
	"ASCA Suffix", "Agility", "RS-E-OP", "Regular Standard Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "RV-N-OP", "Regular Veteran Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "RV-O-OP", "Regular Veteran Open Outstanding Performance",
	"ASCA Suffix", "Agility", "RV-E-OP", "Regular Veteran Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "RJ-N-OP", "Regular Junior Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "RJ-O-OP", "Regular Junior Open Outstanding Performance",
	"ASCA Suffix", "Agility", "RJ-E-OP", "Regular Junior Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "JS-N-OP", "Jumpers Standard Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "JS-O-OP", "Jumpers Standard Open Outstanding Performance",
	"ASCA Suffix", "Agility", "JS-E-OP", "Jumpers Standard Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "JV-N-OP", "Jumpers Veteran Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "JV-O-OP", "Jumpers Veteran Open Outstanding Performance",
	"ASCA Suffix", "Agility", "JV-E-OP", "Jumpers Veteran Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "JJ-N-OP", "Jumpers Junior Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "JJ-O-OP", "Jumpers Junior Open Outstanding Performance",
	"ASCA Suffix", "Agility", "JJ-E-OP", "Jumpers Junior Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "GS-N-OP", "Gamblers Standard Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "GS-O-OP", "Gamblers Standard Open Outstanding Performance",
	"ASCA Suffix", "Agility", "GS-E-OP", "Gamblers Standard Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "GV-N-OP", "Gamblers Veteran Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "GV-O-OP", "Gamblers Veteran Open Outstanding Performance",
	"ASCA Suffix", "Agility", "GV-E-OP", "Gamblers Veteran Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "GJ-N-OP", "Gamblers Junior Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "GJ-O-OP", "Gamblers Junior Open Outstanding Performance",
	"ASCA Suffix", "Agility", "GJ-E-OP", "Gamblers Junior Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "RS-N-SP", "Regular Standard Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "RS-O-SP", "Regular Standard Open Superior Performance",
	"ASCA Suffix", "Agility", "RS-E-SP", "Regular Standard Elite Superior Performance",
	"ASCA Suffix", "Agility", "RV-N-SP", "Regular Veteran Novice Superior Performance",
	"ASCA Suffix", "Agility", "RV-O-SP", "Regular Veteran Open Superior Performance",
	"ASCA Suffix", "Agility", "RV-E-SP", "Regular Veteran Elite Superior Performance",
	"ASCA Suffix", "Agility", "RJ-N-SP", "Regular Junior Novice Superior Performance",
	"ASCA Suffix", "Agility", "RJ-O-SP", "Regular Junior Open Superior Performance",
	"ASCA Suffix", "Agility", "RJ-E-SP", "Regular Junior Elite Superior Performance",
	"ASCA Suffix", "Agility", "JS-N-SP", "Jumpers Standard Novice Superior Performance",
	"ASCA Suffix", "Agility", "JS-O-SP", "Jumpers Standard Open Superior Performance",
	"ASCA Suffix", "Agility", "JS-E-SP", "Jumpers Standard Elite Superior Performance",
	"ASCA Suffix", "Agility", "JV-N-SP", "Jumpers Veteran Novice Superior Performance",
	"ASCA Suffix", "Agility", "JV-O-SP", "Jumpers Veteran Open Superior Performance",
	"ASCA Suffix", "Agility", "JV-E-SP", "Jumpers Veteran Elite Superior Performance",
	"ASCA Suffix", "Agility", "JJ-N-SP", "Jumpers Junior Novice Superior Performance",
	"ASCA Suffix", "Agility", "JJ-O-SP", "Jumpers Junior Open Superior Performance",
	"ASCA Suffix", "Agility", "JJ-E-SP", "Jumpers Junior Elite Superior Performance",
	"ASCA Suffix", "Agility", "GS-N-SP", "Gamblers Standard Novice Superior Performance",
	"ASCA Suffix", "Agility", "GS-O-SP", "Gamblers Standard Open Superior Performance",
	"ASCA Suffix", "Agility", "GS-E-SP", "Gamblers Standard Elite Superior Performance",
	"ASCA Suffix", "Agility", "GV-N-SP", "Gamblers Veteran Novice Superior Performance",
	"ASCA Suffix", "Agility", "GV-O-SP", "Gamblers Veteran Open Superior Performance",
	"ASCA Suffix", "Agility", "GV-E-SP", "Gamblers Veteran Elite Superior Performance",
	"ASCA Suffix", "Agility", "GJ-N-SP", "Gamblers Junior Novice Superior Performance",
	"ASCA Suffix", "Agility", "GJ-O-SP", "Gamblers Junior Open Superior Performance",
	"ASCA Suffix", "Agility", "GJ-E-SP", "Gamblers Junior Elite Superior Performance",
	"ASCA Prefix", "Agility", "ATCH", "Agility Trial Champion",
	"ASCA Prefix", "Agility", "ATCH2", "Agility Trial Champion 2",
	"ASCA Prefix", "Agility", "ATCH3", "Agility Trial Champion 3",
	"ASCA Prefix", "Agility", "ATCH4", "Agility Trial Champion 4",
	"ASCA Prefix", "Agility", "ATCH5", "Agility Trial Champion 5",
	"ASCA Suffix", "Agility", "RSA-N", "Regular Standard Novice",
	"ASCA Suffix", "Agility", "RSA-O", "Regular Standard Open",
	"ASCA Suffix", "Agility", "RSA-E", "Regular Standard Elite",
	"ASCA Suffix", "Agility", "RSDA-N", "Regular Senior Dog Novice",
	"ASCA Suffix", "Agility", "RSDA-O", "Regular Senior Dog Open",
	"ASCA Suffix", "Agility", "RSDA-E", "Regular Senior Dog Elite",
	"ASCA Suffix", "Agility", "JSA-N", "Jumpers Standard Novice",
	"ASCA Suffix", "Agility", "JSA-O", "Jumpers Standard Open",
	"ASCA Suffix", "Agility", "JSA-E", "Jumpers Standard Elite",
	"ASCA Suffix", "Agility", "JSDA-N", "Jumpers Senior Dog Novice",
	"ASCA Suffix", "Agility", "JSDA-O", "Jumpers Senior Dog Open",
	"ASCA Suffix", "Agility", "JSDA-E", "Jumpers Senior Dog Elite",
	"ASCA Suffix", "Agility", "GSA-N", "Gamblers Standard Novice",
	"ASCA Suffix", "Agility", "GSA-O", "Gamblers Standard Open",
	"ASCA Suffix", "Agility", "GSA-E", "Gamblers Standard Elite",
	"ASCA Suffix", "Agility", "JSDA-N", "Gamblers Senior Dog Novice",
	"ASCA Suffix", "Agility", "JSDA-O", "Gamblers Senior Dog Open",
	"ASCA Suffix", "Agility", "JSDA-E", "Gamblers Senior Dog Elite",
	"ASCA Suffix", "Agility", "RSA-N-OP", "Regular Standard Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "RSA-O-OP", "Regular Standard Open Outstanding Performance",
	"ASCA Suffix", "Agility", "RSA-E-OP", "Regular Standard Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "RSDA-N-OP", "Regular Veteran Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "RSDA-O-OP", "Regular Veteran Open Outstanding Performance",
	"ASCA Suffix", "Agility", "RSDA-E-OP", "Regular Veteran Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "JSA-N-OP", "Jumpers Standard Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "JSA-O-OP", "Jumpers Standard Open Outstanding Performance",
	"ASCA Suffix", "Agility", "JSA-E-OP", "Jumpers Standard Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "JSDA-N-OP", "Jumpers Veteran Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "JSDA-O-OP", "Jumpers Veteran Open Outstanding Performance",
	"ASCA Suffix", "Agility", "JSDA-E-OP", "Jumpers Veteran Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "GSA-N-OP", "Gamblers Standard Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "GSA-O-OP", "Gamblers Standard Open Outstanding Performance",
	"ASCA Suffix", "Agility", "GSA-E-OP", "Gamblers Standard Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "GSDA-N-OP", "Gamblers Veteran Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "GSDA-O-OP", "Gamblers Veteran Open Outstanding Performance",
	"ASCA Suffix", "Agility", "GSDA-E-OP", "Gamblers Veteran Elite Outstanding Performance",
	"ASCA Suffix", "Agility", "RSA-N-SP", "Regular Standard Novice Outstanding Performance",
	"ASCA Suffix", "Agility", "RSA-O-SP", "Regular Standard Open Superior Performance",
	"ASCA Suffix", "Agility", "RSA-E-SP", "Regular Standard Elite Superior Performance",
	"ASCA Suffix", "Agility", "RSDA-N-SP", "Regular Veteran Novice Superior Performance",
	"ASCA Suffix", "Agility", "RSDA-O-SP", "Regular Veteran Open Superior Performance",
	"ASCA Suffix", "Agility", "RSDA-E-SP", "Regular Veteran Elite Superior Performance",
	"ASCA Suffix", "Agility", "JSA-N-SP", "Jumpers Standard Novice Superior Performance",
	"ASCA Suffix", "Agility", "JSA-O-SP", "Jumpers Standard Open Superior Performance",
	"ASCA Suffix", "Agility", "JSA-E-SP", "Jumpers Standard Elite Superior Performance",
	"ASCA Suffix", "Agility", "JSDA-N-SP", "Jumpers Veteran Novice Superior Performance",
	"ASCA Suffix", "Agility", "JSDA-O-SP", "Jumpers Veteran Open Superior Performance",
	"ASCA Suffix", "Agility", "JSDA-E-SP", "Jumpers Veteran Elite Superior Performance",
	"ASCA Suffix", "Agility", "GSA-N-SP", "Gamblers Standard Novice Superior Performance",
	"ASCA Suffix", "Agility", "GSA-O-SP", "Gamblers Standard Open Superior Performance",
	"ASCA Suffix", "Agility", "GSA-E-SP", "Gamblers Standard Elite Superior Performance",
	"ASCA Suffix", "Agility", "GSDA-N-SP", "Gamblers Veteran Novice Superior Performance",
	"ASCA Suffix", "Agility", "GSDA-O-SP", "Gamblers Veteran Open Superior Performance",
	"ASCA Suffix", "Agility", "GSDA-E-SP", "Gamblers Veteran Elite Superior Performance",
	"ASCA Prefix", "Agility", "ACE", "ACE Agility Trial Champion",
	"ASCA Prefix", "Agility", "ACE2", "ACE Agility Trial Champion 2",
	"ASCA Prefix", "Agility", "ACE3", "ACE Agility Trial Champion 3",
	"ASCA Prefix", "Agility", "ACE4", "ACE Agility Trial Champion 4",
	"ASCA Prefix", "Agility", "ACE5", "ACE Agility Trial Champion 5",
	"ASCA Prefix", "Versatility", "VCH", "Versatility Champion",
	"ASCA Prefix", "Versatility", "SVCH", "Supreme Versatility Champion",
	"ASCA Prefix", "Performance", "PCH", "Performance Champion",
	"ASCA Prefix", "Performance", "SPCH", "Supreme Performance Champion",
	"ASCA Prefix", "Hall of Fame", "HOF", "Hall of Fame Dam / Sire",
	"ASCA Suffix", "DNA", "DNA-CP", "DNA Certified Profiled",
	"ASCA Suffix", "DNA", "DNA-VP", "DNA Verified Parentage",
	"ASCA Suffix", "Dock Diving", "LS-N", "Launch Spring Novice",
	"ASCA Suffix", "Dock Diving", "LS-A", "Launch Spring Advanced",
	"ASCA Suffix", "Dock Diving", "LS-E", "Launch Spring Excellent",
	"ASCA Suffix", "Dock Diving", "LS-M", "Launch Spring Master",
	"ASCA Suffix", "Dock Diving", "LC-N", "Launch Classic Novice",
	"ASCA Suffix", "Dock Diving", "LC-A", "Launch Classic Advanced",
	"ASCA Suffix", "Dock Diving", "LC-E", "Launch Classic Excellent",
	"ASCA Suffix", "Dock Diving", "LC-M", "Launch Classic Master",
	"ASCA Suffix", "Dock Diving", "LD-N", "Launch Deluxe Novice",
	"ASCA Suffix", "Dock Diving", "LD-A", "Launch Deluxe Advanced",
	"ASCA Suffix", "Dock Diving", "LD-E", "Launch Deluxe Excellent",
	"ASCA Suffix", "Dock Diving", "LD-M", "Launch Deluxe Master",
	"ASCA Suffix", "Dock Diving", "LF-N", "Launch Fly Novice",
	"ASCA Suffix", "Dock Diving", "LF-A", "Launch Fly Advanced",
	"ASCA Suffix", "Dock Diving", "LF-E", "Launch Fly Excellent",
	"ASCA Suffix", "Dock Diving", "LF-M", "Launch Fly Master",
	"ASCA Suffix", "Dock Diving", "LE-N", "Launch Elite Novice",
	"ASCA Suffix", "Dock Diving", "LE-A", "Launch Elite Advanced",
	"ASCA Suffix", "Dock Diving", "LE-E", "Launch Elite Excellent",
	"ASCA Suffix", "Dock Diving", "LE-M", "Launch Elite Master",
	"ASCA Suffix", "Dock Diving", "LP-N", "Launch Pro Novice",
	"ASCA Suffix", "Dock Diving", "LP-A", "Launch Pro Advanced",
	"ASCA Suffix", "Dock Diving", "LP-E", "Launch Pro Excellent",
	"ASCA Suffix", "Dock Diving", "LP-M", "Launch Pro Master",
	"ASCA Suffix", "Dock Diving", "LU-N", "Launch Ultra Novice",
	"ASCA Suffix", "Dock Diving", "LU-A", "Launch Ultra Advanced",
	"ASCA Suffix", "Dock Diving", "LU-E", "Launch Ultra Excellent",
	"ASCA Suffix", "Dock Diving", "LU-M", "Launch Ultra Master",
	"ASCA Suffix", "Dock Diving", "FS-N", "Fetch It Spring Novice",
	"ASCA Suffix", "Dock Diving", "FS-A", "Fetch It Spring Advanced",
	"ASCA Suffix", "Dock Diving", "FS-E", "Fetch It Spring Excellent",
	"ASCA Suffix", "Dock Diving", "FS-M", "Fetch It Spring Master",
	"ASCA Suffix", "Dock Diving", "FC-N", "Fetch It Classic Novice",
	"ASCA Suffix", "Dock Diving", "FC-A", "Fetch It Classic Advanced",
	"ASCA Suffix", "Dock Diving", "FC-E", "Fetch It Classic Excellent",
	"ASCA Suffix", "Dock Diving", "FC-M", "Fetch It Classic Master",
	"ASCA Suffix", "Dock Diving", "FD-N", "Fetch It Deluxe Novice",
	"ASCA Suffix", "Dock Diving", "FD-A", "Fetch It Deluxe Advanced",
	"ASCA Suffix", "Dock Diving", "FD-E", "Fetch It Deluxe Excellent",
	"ASCA Suffix", "Dock Diving", "FD-M", "Fetch It Deluxe Master",
	"ASCA Suffix", "Dock Diving", "FF-N", "Fetch It Fly Novice",
	"ASCA Suffix", "Dock Diving", "FF-A", "Fetch It Fly Advanced",
	"ASCA Suffix", "Dock Diving", "FF-E", "Fetch It Fly Excellent",
	"ASCA Suffix", "Dock Diving", "FF-M", "Fetch It Fly Master",
	"ASCA Suffix", "Dock Diving", "FE-N", "Fetch It Elite Novice",
	"ASCA Suffix", "Dock Diving", "FE-A", "Fetch It Elite Advanced",
	"ASCA Suffix", "Dock Diving", "FE-E", "Fetch It Elite Excellent",
	"ASCA Suffix", "Dock Diving", "FE-M", "Fetch It Elite Master",
	"ASCA Prefix", "Dock Diving", "DTCH-Ls", "Dock Trial Champion Launch Spring",
	"ASCA Prefix", "Dock Diving", "DTCH-Lc", "Dock Trial Champion Launch Classic",
	"ASCA Prefix", "Dock Diving", "DTCH-Ld", "Dock Trial Champion Launch Deluxe",
	"ASCA Prefix", "Dock Diving", "DTCH-Lf", "Dock Trial Champion Launch Fly",
	"ASCA Prefix", "Dock Diving", "DTCH-Le", "Dock Trial Champion Launch Elite",
	"ASCA Prefix", "Dock Diving", "DTCH-Lp", "Dock Trial Champion Launch Pro",
	"ASCA Prefix", "Dock Diving", "DTCH-Lu", "Dock Trial Champion Launch Ultra",
	"ASCA Prefix", "Dock Diving", "DTCH-Fs", "Dock Trial Champion Fetch It Spring",
	"ASCA Prefix", "Dock Diving", "DTCH-Fc", "Dock Trial Champion Fetch It Classic",
	"ASCA Prefix", "Dock Diving", "DTCH-Fd", "Dock Trial Champion Fetch It Deluxe",
	"ASCA Prefix", "Dock Diving", "DTCH-Ff", "Dock Trial Champion Fetch It Fly",
	"ASCA Prefix", "Dock Diving", "DTCH-Fe", "Dock Trial Champion Fetch It Elite",
	"CPE Prefix", "Agility", "C-ATE", "CPE Agility Team Extraordinaire",
	"CPE Prefix", "Agility", "CT-ATE", "CPE Enthusiast Agility Team Extraordinaire",
	"CPE Prefix", "Agility", "CS-ATE", "CPE Specialist Agility Team Extraordinaire",
	"CPE Prefix", "Agility", "C-ATCH", "CPE Agility Trial Champion",
	"CPE Prefix", "Agility", "CT-ATCH", "CPE Enthusiast Agility Trial Champion",
	"CPE Prefix", "Agility", "CS-ATCH", "CPE Specialist Agility Trial Champion",
	"CPE Prefix", "Agility", "SpEX", "Specialist Extraordinaire",
	"CPE Prefix", "Agility", "SpCH", "Specialist Champion",
	"CPE Prefix", "Canine Scent Sport", "C-SNITE", "CPE Sniffing Team Extraordinaire",
	"CPE Prefix", "Canine Scent Sport", "C-SNITCH", "CPE Sniffing Team Champion",
	"CPE Prefix", "Canine Scent Sport", "C-CSSTE", "CPE Canine Scent Sport Team Extraordinaire",
	"CPE Prefix", "SpeedWay", "C-SWGL", "CPE Speedway Gold Legendary",
	"CPE Prefix", "SpeedWay", "C-SWPL", "CPE SpeedWay Platinum Legendary",
	"CPE Suffix", "Agility", "L1-PLT", "Level 1 Point Level Title",
	"CPE Suffix", "Agility", "L1T-PLT", "Level 1 Enthusiast Point Level Title",
	"CPE Suffix", "Agility", "L1S-PLT", "Level 1 Specialist Point Level Title",
	"CPE Suffix", "Agility", "L2-PLT", "Level 2 Point Level Title",
	"CPE Suffix", "Agility", "L2T-PLT", "Level 2 Enthusiast Point Level Title",
	"CPE Suffix", "Agility", "L2S-PLT", "Level 2 Specialist Point Level Title",
	"CPE Suffix", "Agility", "L3-PLT", "Level 3 Point Level Title",
	"CPE Suffix", "Agility", "L3T-PLT", "Level 3 Enthusiast Point Level Title",
	"CPE Suffix", "Agility", "L3S-PLT", "Level 3 Specialist Point Level Title",
	"CPE Suffix", "Agility", "L4-PLT", "Level 4 Point Level Title",
	"CPE Suffix", "Agility", "L4T-PLT", "Level 4 Enthusiast Point Level Title",
	"CPE Suffix", "Agility", "L4S-PLT", "Level 4 Specialist Point Level Title",
	"CPE Suffix", "Agility", "L5-PLT", "Level 5 Point Level Title",
	"CPE Suffix", "Agility", "L5T-PLT", "Level 5 Enthusiast Point Level Title",
	"CPE Suffix", "Agility", "L5S-PLT", "Level 5 Specialist Point Level Title",
	"CPE Suffix", "Agility", "CL1-R", "CPE Level 1 Standard",
	"CPE Suffix", "Agility", "CL1-H", "CPE Level 1 Handler",
	"CPE Suffix", "Agility", "CL1-S", "CPE Level 1 Strategy",
	"CPE Suffix", "Agility", "CL1-F", "CPE Level 1 Fun",
	"CPE Suffix", "Agility", "CL1", "CPE Level 1",
	"CPE Suffix", "Agility", "CL2-R", "CPE Level 2 Standard",
	"CPE Suffix", "Agility", "CL2-H", "CPE Level 2 Handler",
	"CPE Suffix", "Agility", "CL2-S", "CPE Level 2 Strategy",
	"CPE Suffix", "Agility", "CL2-F", "CPE Level 2 Fun",
	"CPE Suffix", "Agility", "CL2", "CPE Level 2",
	"CPE Suffix", "Agility", "CL3-R", "CPE Level 3 Standard",
	"CPE Suffix", "Agility", "CL3-H", "CPE Level 3 Handler",
	"CPE Suffix", "Agility", "CL3-S", "CPE Level 3 Strategy",
	"CPE Suffix", "Agility", "CL3-F", "CPE Level 3 Fun",
	"CPE Suffix", "Agility", "CL3", "CPE Level 3",
	"CPE Suffix", "Agility", "CL4-R", "CPE Level 4 Standard",
	"CPE Suffix", "Agility", "CL4-H", "CPE Level 4 Handler",
	"CPE Suffix", "Agility", "CL4-S", "CPE Level 4 Strategy",
	"CPE Suffix", "Agility", "CL4-F", "CPE Level 4 Fun",
	"CPE Suffix", "Agility", "CL4", "CPE Level 4",
	"CPE Suffix", "Agility", "CTL1-R", "CPE Enthusiast Level 1 Standard",
	"CPE Suffix", "Agility", "CTL1-H", "CPE Enthusiast Level 1 Handler",
	"CPE Suffix", "Agility", "CTL1-S", "CPE Enthusiast Level 1 Strategy",
	"CPE Suffix", "Agility", "CTL1-F", "CPE Enthusiast Level 1 Fun",
	"CPE Suffix", "Agility", "CTL1", "CPE Enthusiast Level 1",
	"CPE Suffix", "Agility", "CTL2-R", "CPE Enthusiast Level 2 Standard",
	"CPE Suffix", "Agility", "CTL2-H", "CPE Enthusiast Level 2 Handler",
	"CPE Suffix", "Agility", "CTL2-S", "CPE Enthusiast Level 2 Strategy",
	"CPE Suffix", "Agility", "CTL2-F", "CPE Enthusiast Level 2 Fun",
	"CPE Suffix", "Agility", "CTL2", "CPE Enthusiast Level 2",
	"CPE Suffix", "Agility", "CTL3-R", "CPE Enthusiast Level 3 Standard",
	"CPE Suffix", "Agility", "CTL3-H", "CPE Enthusiast Level 3 Handler",
	"CPE Suffix", "Agility", "CTL3-S", "CPE Enthusiast Level 3 Strategy",
	"CPE Suffix", "Agility", "CTL3-F", "CPE Enthusiast Level 3 Fun",
	"CPE Suffix", "Agility", "CTL3", "CPE Enthusiast Level 3",
	"CPE Suffix", "Agility", "CTL4-R", "CPE Enthusiast Level 4 Standard",
	"CPE Suffix", "Agility", "CTL4-H", "CPE Enthusiast Level 4 Handler",
	"CPE Suffix", "Agility", "CTL4-S", "CPE Enthusiast Level 4 Strategy",
	"CPE Suffix", "Agility", "CTL4-F", "CPE Enthusiast Level 4 Fun",
	"CPE Suffix", "Agility", "CTL4", "CPE Enthusiast Level 4",
	"CPE Suffix", "Agility", "CSL1-R", "CPE Specialist Level 1 Standard",
	"CPE Suffix", "Agility", "CSL1-H", "CPE Specialist Level 1 Handler",
	"CPE Suffix", "Agility", "CSL1-S", "CPE Specialist Level 1 Strategy",
	"CPE Suffix", "Agility", "CSL1-F", "CPE Specialist Level 1 Fun",
	"CPE Suffix", "Agility", "CSL1", "CPE Specialist Level 1",
	"CPE Suffix", "Agility", "CSL2-R", "CPE Specialist Level 2 Standard",
	"CPE Suffix", "Agility", "CSL2-H", "CPE Specialist Level 2 Handler",
	"CPE Suffix", "Agility", "CSL2-S", "CPE Specialist Level 2 Strategy",
	"CPE Suffix", "Agility", "CSL2-F", "CPE Specialist Level 2 Fun",
	"CPE Suffix", "Agility", "CSL2", "CPE Specialist Level 2",
	"CPE Suffix", "Agility", "CSL3-R", "CPE Specialist Level 3 Standard",
	"CPE Suffix", "Agility", "CSL3-H", "CPE Specialist Level 3 Handler",
	"CPE Suffix", "Agility", "CSL3-S", "CPE Specialist Level 3 Strategy",
	"CPE Suffix", "Agility", "CSL3-F", "CPE Specialist Level 3 Fun",
	"CPE Suffix", "Agility", "CSL3", "CPE Specialist Level 3",
	"CPE Suffix", "Agility", "CSL4-R", "CPE Specialist Level 4 Standard",
	"CPE Suffix", "Agility", "CSL4-H", "CPE Specialist Level 4 Handler",
	"CPE Suffix", "Agility", "CSL4-S", "CPE Specialist Level 4 Strategy",
	"CPE Suffix", "Agility", "CSL4-F", "CPE Specialist Level 4 Fun",
	"CPE Suffix", "Agility", "CSL4", "CPE Specialist Level 4",
	"CPE Prefix", "Agility", "ChST", "Champion Standard",
	"CPE Prefix", "Agility", "ChCL", "Champion Colors",
	"CPE Prefix", "Agility", "ChWC", "Champion Wildcard",
	"CPE Prefix", "Agility", "ChSN", "Champion Snooker",
	"CPE Prefix", "Agility", "ChJP", "Champion Jackpot",
	"CPE Prefix", "Agility", "ChFH", "Champion FullHouse",
	"CPE Prefix", "Agility", "ChJU", "Champion Jumpers",
	"CPE Prefix", "Agility", "TChST", "Enthusiast Champion Standard",
	"CPE Prefix", "Agility", "TChCL", "Enthusiast Champion Colors",
	"CPE Prefix", "Agility", "TChWC", "Enthusiast Champion Wildcard",
	"CPE Prefix", "Agility", "TChSN", "Enthusiast Champion Snooker",
	"CPE Prefix", "Agility", "TChJP", "Enthusiast Champion Jackpot",
	"CPE Prefix", "Agility", "TChFH", "Enthusiast Champion FullHouse",
	"CPE Prefix", "Agility", "TChJU", "Enthusiast Champion Jumpers",
	"CPE Prefix", "Agility", "SpChST", "Specialist Champion Standard",
	"CPE Prefix", "Agility", "SpChCL", "Specialist Champion Colors",
	"CPE Prefix", "Agility", "SpChWC", "Specialist Champion Wildcard",
	"CPE Prefix", "Agility", "SpChSN", "Specialist Champion Snooker",
	"CPE Prefix", "Agility", "SpChJP", "Specialist Champion Jackpot",
	"CPE Prefix", "Agility", "SpChFH", "Specialist Champion FullHouse",
	"CPE Prefix", "Agility", "SpChJU", "Specialist Champion Jumpers",
	"CPE Prefix", "Agility", "ExST", "Extraordinaire Standard",
	"CPE Prefix", "Agility", "ExCL", "Extraordinaire Colors",
	"CPE Prefix", "Agility", "ExWC", "Extraordinaire Wildcard",
	"CPE Prefix", "Agility", "ExSN", "Extraordinaire Snooker",
	"CPE Prefix", "Agility", "ExJP", "Extraordinaire Jackpot",
	"CPE Prefix", "Agility", "ExFH", "Extraordinaire FullHouse",
	"CPE Prefix", "Agility", "ExJU", "Extraordinaire Jumpers",
	"CPE Prefix", "Agility", "TExST", "Enthusiast Extraordinaire Standard",
	"CPE Prefix", "Agility", "TExCL", "Enthusiast Extraordinaire Colors",
	"CPE Prefix", "Agility", "TExWC", "Enthusiast Extraordinaire Wildcard",
	"CPE Prefix", "Agility", "TExSN", "Enthusiast Extraordinaire Snooker",
	"CPE Prefix", "Agility", "TExJP", "Enthusiast Extraordinaire Jackpot",
	"CPE Prefix", "Agility", "TExFH", "Enthusiast Extraordinaire FullHouse",
	"CPE Prefix", "Agility", "TExJU", "Enthusiast Extraordinaire Jumpers",
	"CPE Prefix", "Agility", "SpExST", "Specialist Extraordinaire Standard",
	"CPE Prefix", "Agility", "SpExCL", "Specialist Extraordinaire Colors",
	"CPE Prefix", "Agility", "SpExWC", "Specialist Extraordinaire Wildcard",
	"CPE Prefix", "Agility", "SpExSN", "Specialist Extraordinaire Snooker",
	"CPE Prefix", "Agility", "SpExJP", "Specialist Extraordinaire Jackpot",
	"CPE Prefix", "Agility", "SpExFH", "Specialist Extraordinaire FullHouse",
	"CPE Prefix", "Agility", "SpExJU", "Specialist Extraordinaire Jumpers",
	"CPE Suffix", "Canine Scent Sport", "CCSS-L1", "CPE Canine Scent Sport Level 1",
	"CPE Suffix", "Canine Scent Sport", "CCSS-L2", "CPE Canine Scent Sport Level 2",
	"CPE Suffix", "Canine Scent Sport", "CCSS-L3", "CPE Canine Scent Sport Level 3",
	"CPE Suffix", "Canine Scent Sport", "CCSS-LCH", "CPE Canine Scent Sport Level CH",
	"CPE Suffix", "Canine Scent Sport", "CCSS-LEX", "CPE Canine Scent Sport Level EX",
	"CPE Suffix", "SpeedWay", "C-SWE", "Speedway Elite",
	"CPE Suffix", "SpeedWay", "C-SWP", "Speedway Pro",
	"CPE Suffix", "SpeedWay", "C-SWM", "Speedway Master",
	"CPE Suffix", "SpeedWay", "C-SWBL", "Speedway Bronze Legendary",
	"CPE Suffix", "SpeedWay", "C-SWSL", "Speedway Silver Legendary",
	"CPE Suffix", "SpeedWay", "C-SWGL", "Speedway Gold Legendary",
	"CPE Suffix", "SpeedWay", "C-SWPL", "Speedway Platinum Legendary",
	"CPE Suffix", "SpeedWay", "C-SWPL2", "Speedway Platinum Legendary 2",
	"CPE Suffix", "SpeedWay", "C-SWPL3", "Speedway Platinum Legendary 3",
	"CPE Suffix", "SpeedWay", "C-SWPL4", "Speedway Platinum Legendary 4",
	"CPE Suffix", "SpeedWay", "C-SWPL5", "Speedway Platinum Legendary 5",
	"CPE Suffix", "SpeedWay", "C-SWJrE", "Speedway Jr Handler Elite",
	"CPE Suffix", "SpeedWay", "C-SWJrP", "Speedway Jr Handler Pro",
	"CPE Suffix", "SpeedWay", "C-SWJrM", "Speedway Jr Handler Master",
	"CPE Suffix", "SpeedWay", "C-SWJrBL", "Speedway Jr Handler Bronze Legendary",
	"CPE Suffix", "SpeedWay", "C-SWJrSL", "Speedway Jr Handler Silver Legendary",
	"CPE Suffix", "SpeedWay", "C-SWJrGL", "Speedway Jr Handler Gold Legendary",
	"CPE Suffix", "SpeedWay", "C-SWJrPL", "Speedway Jr Handler Platinum Legendary",
	"CPE Suffix", "SpeedWay", "C-SWJrPL2", "Speedway Jr Handler Platinum Legendary 2",
	"CPE Suffix", "SpeedWay", "C-SWJrPL3", "Speedway Jr Handler Platinum Legendary 3",
	"CPE Suffix", "SpeedWay", "C-SWJrPL4", "Speedway Jr Handler Platinum Legendary 4",
	"CPE Suffix", "SpeedWay", "C-SWJrPL5", "Speedway Jr Handler Platinum Legendary 5",
	"UKC Prefix", "Bench Show (Beagle)", "WSHOWCH2", "Hunting Beagle World Show Champion 2X",
	"UKC Prefix", "Bench Show (Beagle)", "WSHOWCH", "Hunting Beagle World Show Champion",
	"UKC Prefix", "Bench Show (Beagle)", "NGRC", "National Grand Show Champion",
	"UKC Prefix", "Bench Show (Beagle)", "GRCH", "Grand Show Champion",
	"UKC Prefix", "Bench Show (Beagle)", "CH", "Show Champion",
	"UKC Prefix", "Hunting Beagle Event", "WORLDHBCH", "World Hunting Beagle Champion",
	"UKC Prefix", "Hunting Beagle Event", "NGRHBC", "National Grand Hunting Beagle Champion",
	"UKC Prefix", "Hunting Beagle Event", "GRHBCH", "Grand Hunting Beagle Champion",
	"UKC Prefix", "Hunting Beagle Event", "HBCH", "Hunting Beagle Champion",
	"UKC Prefix", "Large Pack Event", "GRFCH", "Grand Field Champion",
	"UKC Prefix", "Large Pack Event", "FCH", "Field Champion",
	"UKC Prefix", "Performance Peak Event", "WORLDPCH2X", "World Performance Pack Champion 2X",
	"UKC Prefix", "Performance Peak Event", "WORLDPCH", "World Performance Pack Champion",
	"UKC Prefix", "Performance Peak Event", "GRPCH", "Grand Performance Pack Champion",
	"UKC Prefix", "Performance Peak Event", "PCH", "Performance Pack Champion",
	"UKC Prefix", "Bench Show (Coonhound)", "WSHOWCH", "World Show Champion",
	"UKC Prefix", "Bench Show (Coonhound)", "WSHOWCH2X", "World Show Champion 2X",
	"UKC Prefix", "Bench Show (Coonhound)", "NGRCH", "National Grand Show Champion",
	"UKC Prefix", "Bench Show (Coonhound)", "NGRCH", "National Grand Show Champion 2X",
	"UKC Prefix", "Bench Show (Coonhound)", "NGRC", "National Grand Show Champion",
	"UKC Prefix", "Bench Show (Coonhound)", "GRCH", "Grand Show Champion",
	"UKC Prefix", "Bench Show (Coonhound)", "CH", "Show Champion",
	"UKC Prefix", "Bench Show (Coonhound)", "GRCHHOF", "Grand Champion Hall of Fame",
	"UKC Prefix", "Field Trial (Coonhound)", "GRFCH", "Grand Field Champion",
	"UKC Prefix", "Field Trial (Coonhound)", "FCH", "Field Champion",
	"UKC Prefix", "Field Trial (Coonhound)", "GRFCHHOF", "Grand Field Champion Hall of Fame",
	"UKC Suffix", "Hunt Test (Coonhound)", "HTX", "Hunt Test Excellence", 
	"UKC Prefix", "Nite Hunt (Coonhound)", "WLDNITECH", "World Nite Hunt Champion",
	"UKC Prefix", "Nite Hunt (Coonhound)", "NATLDC", "National Dual Champion",
	"UKC Prefix", "Nite Hunt (Coonhound)", "NGRNCH", "National Grand Nite Champion",
	"UKC Prefix", "Nite Hunt (Coonhound)", "GRNITECH", "Grand Nite Champion",
	"UKC Prefix", "Nite Hunt (Coonhound)", "NITECH", "Nite Champion",
	"UKC Prefix", "Nite Hunt (Coonhound)", "GRNITECHHOF", "Grand Nite Champion Hall of Fame",
	"UKC Prefix", "Water Race", "GRWCH", "Grand Water Champion",
	"UKC Prefix", "Water Race", "WCH", "Water Champion",
	"UKC Prefix", "Water Race", "GRWCHHOF", "Grand Water Champion Hall of Fame",
	"UKC Prefix", "Bench Show (Cur/Feist)", "GRCH", "Grand Show Champion",
	"UKC Prefix", "Bench Show (Cur/Feist)", "CH", "Show Champion",
	"UKC Prefix", "Coon Hunt (Cur/Feist)", "GRNITECH", "Grand Nite Champion",
	"UKC Prefix", "Coon Hunt (Cur/Feist)", "NITECH", "Nite Champion",
	"UKC Suffix", "Hunt Test (Cur/Feist)", "HTX", "Hunt Test Excellence",
	"UKC Prefix", "Squirrel Hunt", "WORLDSQDOGCH", "World Squirrel Dog Champion",
	"UKC Prefix", "Squirrel Hunt", "GRSQCH", "Grand Squirrel Champion",
	"UKC Prefix", "Squirrel Hunt", "SQCH", "Squirrel Champion",
	"UKC Prefix", "Squirrel Hunt", "GRSQCHHOF", "Grand Squirrel Champion Hall of Fame",
	"UKC Prefix", "Hunt Test (Hunting Retriever)", "GRHRCH", "Grand Hunting Retriever Champion",
	"UKC Prefix", "Hunt Test (Hunting Retriever)", "HRCH", "Hunting Retriever Champion",
	"UKC Prefix", "Hunt Test (Hunting Retriever)", "HR", "Hunting Retriever",
	"UKC Prefix", "Hunt Test (Hunting Retriever)", "SHR", "Started Hunting Retriever",
	"UKC Prefix", "Hunt Test (Hunting Retriever)", "UH", "Upland Hunter",
	"UKC Suffix", "Hunt Test (Hunting Retriever)", "HOF", "Hall of Fame",
	"UKC Prefix", "Field Trial (Pointing Dog)", "GRCHF", "Grand Champion of the Field",
	"UKC Prefix", "Field Trial (Pointing Dog)", "CHF", "Champion of the Field",
	"UKC Prefix", "Field Trial (Pointing Dog)", "TR", "Trialer",
	"UKC Prefix", "Field Trial (Pointing Dog)", "GUN", "Gun Dog",
	"UKC Prefix", "Field Trial (Pointing Dog)", "HUNT", "1st Level Gun Dog",
	"UKC Prefix", "Field Trial (Pointing Dog)", "CHF-W", "Champion of the Field - Wild",
	"UKC Prefix", "Field Trial (Pointing Dog)", "CHF-L", "Champion of the Field - Liberated",
	"UKC Suffix", "Field Trial (Pointing Dog)", "TAN", "Natural Ability Test",
	"UKC Suffix", "Field Trial (Pointing Dog)", "WRT", "Water Retrieve Test",
	"UKC Prefix", "Elite Shed Dog", "ESD", "Elite Shed Dog",
	"UKC Prefix", "Elite Shed Dog", "WSD", "Working Shed Dog",
	"UKC Prefix", "Elite Shed Dog", "CHSD", "Champion Shed Dog",
	"UKC Prefix", "Elite Shed Dog", "GRCHSD", "Grand Champion Shed Dog",
	"UKC Prefix", "Elite Shed Dog", "NCHSD", "National Champion Shed Dog",
	"UKC Suffix", "Elite Shed Dog" , "HOF", "Hall of Fame",
	"APLA Prefix", "American Pointing Labrador Association", "CPR", "Certified Pointing Retriever",
	"APLA Prefix", "American Pointing Labrador Association", "APR", "Advanced Pointing Retriever",
	"APLA Prefix", "American Pointing Labrador Association", "MPR", "Master Pointing Retriever",
	"APLA Prefix", "American Pointing Labrador Association", "GMPR", "Grand Master Pointing Retriever",
	"UFTA Prefix", "United Field Trialers Association", "NF.CH", "UFTA National Field Champion",
	"UFTA Prefix", "United Field Trialers Association", "RNF.CH", "UFTA Reserve National Field Champion",
	"UFTA Prefix", "United Field Trialers Association", "F.CH", "UFTA Field Champion",
	"NSTRA Prefix", "National Shoot To Retrieve", "NTLCH", "NSTRA National Champion",
	"NSTRA Prefix", "National Shoot To Retrieve", "RUNTLCH", "NSTRA Runner Up National Champion",
	"NSTRA Prefix", "National Shoot To Retrieve", "REGCH", "NSTRA Regional Champion",
	"NSTRA Prefix", "National Shoot To Retrieve", "CH", "NSTRA Champion",
	"NSTRA Prefix", "National Shoot To Retrieve", "AMCH", "NSTRA Amateur Champion",
	"NBDC Prefix", "National Bird Dog Circuit", "BDC CH", "Bird Dog Circuit Champion",
	"NBDC Prefix", "National Bird Dog Circuit", "BDC DOY", "Bird Dog Circuit Dog of the Year",
	"NBDC Prefix", "National Bird Dog Circuit", "BDC WC", "Bird Dog Circuit World Champion",
	"NBDC Prefix", "National Bird Dog Circuit", "BDC NC", "Bird Dog Circuit National Champion",
	"NBDC Prefix", "National Bird Dog Circuit", "BDC SM", "Bird Dog Circuit Super Major Win",
	"NBDC Prefix", "National Bird Dog Circuit", "BDC LC", "Bird Dog Circuit Legendary",
	"SRS Prefix", "Super Retriever Series", "SRSC", "Super Retriever Series Champion",
	"SRS Prefix", "Super Retriever Series", "SRSAC", "Super Retriever Series Amateur Champion",
	"SRS Prefix", "Super Retriever Series", "SRSCC", "Super Retriever Series Crown Champion",
	"SRS Prefix", "Super Retriever Series", "SRSACC", "Super Retriever Series Amateur Crown Champion",
	"UKC Prefix", "Agility", "UGRACH", "United Grand Agility Champion",
	"UKC Prefix", "Agility", "UGRACH2", "United Grand Agility Champion 2",
	"UKC Prefix", "Agility", "UGRACH3", "United Grand Agility Champion 3",
	"UKC Prefix", "Agility", "UGRACH4", "United Grand Agility Champion 4",
	"UKC Prefix", "Agility", "UGRACH5", "United Grand Agility Champion 5",
	"UKC Prefix", "Agility", "UACHX", "United Agility Champion Excellent",
	"UKC Prefix", "Agility", "UACH", "United Agility Champion",
	"UKC Prefix", "Agility", "UAGII", "United Agility II",
	"UKC Prefix", "Agility", "UAGI", "United Agility I",
	"UKC Prefix", "Conformation", "CH", "Champion",
	"UKC Prefix", "Conformation", "GRCH", "Grand Champion",
	"UKC Prefix", "Conformation (Coonhound)", "CCH", "Conformation Champion",
	"UKC Prefix", "Conformation (Beagles)", "CCH", "Conformation Champion",
	"UKC Prefix", "Conformation (Cur/Feist)", "CCH", "Conformation Champion",
	"UKC Prefix", "Conformation (Coonhound)", "CGRCH", "Conformation Grand Champion",
	"UKC Prefix", "Conformation (Beagles)", "CGRCH", "Conformation Grand Champion",
	"UKC Prefix", "Conformation (Cur/Feist)", "CGRCH", "Conformation Grand Champion",
	"UKC Prefix", "Conformation", "NBOB", "National Best of Breed",
	"UKC Prefix", "Conformation (American Eskimos)", "NGRCH", "National Grand Champion",
	"UKC Prefix", "Conformation (Toy Fox Terriers)", "NGRCH", "National Grand Champion",
	"UKC Prefix", "Conformation", "EGCH", "Emerald Grand Champion",
	"UKC Prefix", "Conformation", "RGCH", "Ruby Grand Champion",
	"UKC Prefix", "Conformation", "SGCH", "Sapphire Grand Champion",
	"UKC Prefix", "Conformation", "DGCH", "Diamond Grand Champion",
	"UKC Prefix", "Conformation", "ALCH", "Altered Champion",
	"UKC Prefix", "Conformation", "ALGRCH", "Altered Grand Champion",
	"UKC Prefix", "Conformation (Coonhound)", "ALCCH", "Altered Conformation Champion",
	"UKC Prefix", "Conformation (Beagles)", "ALCCH", "Altered Conformation Champion",
	"UKC Prefix", "Conformation (Cur/Feist)", "ALCCH", "Altered Conformation Champion",
	"UKC Prefix", "Conformation (Coonhound)", "ALCGRCH", "Altered Conformation Grand Champion",
	"UKC Prefix", "Conformation (Beagles)", "ALCGRCH", "Altered Conformation Grand Champion",
	"UKC Prefix", "Conformation (Cur/Feist)", "ALCGRCH", "Altered Conformation Grand Champion",
	"UKC Prefix", "Conformation", "AEGCH", "Altered Emerald Grand Champion",
	"UKC Prefix", "Conformation", "ARGCH", "Altered Ruby Grand Champion",
	"UKC Prefix", "Conformation", "ASGCH", "Altered Sapphire Grand Champion",
	"UKC Prefix", "Conformation", "ADGCH", "Altered Diamond Grand Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) Initial Distance Jumping", "UUJ", "United Ultimate Jumper",
	"UKC Prefix", "Dock Jumping (Air Dog) Initial Distance Jumping", "UMJ", "United Master Jumper",
	"UKC Prefix", "Dock Jumping (Air Dog) Initial Distance Jumping", "USJ", "United Senior Jumper",
	"UKC Prefix", "Dock Jumping (Air Dog) Initial Distance Jumping", "UJJ", "United Junior Jumper",
	"UKC Prefix", "Dock Jumping (Air Dog) Initial Distance Jumping", "UNJ", "United Novice Jumper",
	"UKC Prefix", "Dock Jumping (Air Dog) United Distance Jumping Champion", "UUJCH", "United Ultimate Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) United Distance Jumping Champion", "UMJCH", "United Master Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) United Distance Jumping Champion", "USJCH", "United Senior Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) United Distance Jumping Champion", "UJJCH", "United Junior Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) United Distance Jumping Champion", "UNJCH", "United Novice Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) Grand Distance Jumping Champion", "GUJCH", "Grand Ultimate Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) Grand Distance Jumping Champion", "GMJCH", "Grand Master Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) Grand Distance Jumping Champion", "GSJCH", "Grand Senior Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) Grand Distance Jumping Champion", "GJJCH", "Grand Junior Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) Grand Distance Jumping Champion", "GNJCH", "Grand Novice Jumper Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) Initial Ultimate Vertical", "URUV", "United Radical Ultimate Vertical",
	"UKC Prefix", "Dock Jumping (Air Dog) Initial Ultimate Vertical", "USUV", "United Supreme Ultimate Vertical",
	"UKC Prefix", "Dock Jumping (Air Dog) United Ultimate Vertical Champion", "URUVCH", "United Radical Ultimate Vertical Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) United Ultimate Vertical Champion", "USUVCH", "United Supreme Ultimate Vertical Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) Ultimate Vertical Grand Champion", "GRUVCH", "United Grand Radical Ultimate Vertical Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) Ultimate Vertical Grand Champion", "GSUVCH", "United Grand Supreme Ultimate Vertical Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) United Fetch It", "UUF", "United Ultimate Fetch It",
	"UKC Prefix", "Dock Jumping (Air Dog) United Fetch It", "USF", "United Supreme Fetch It",
	"UKC Prefix", "Dock Jumping (Air Dog) United Fetch It Champion", "UUFCH", "United Ultimate Fetch It Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) United Fetch It Champion", "USFCH", "United Ultimate Fetch It Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) United Fetch It Grand Champion", "GUFCH", "United Grand Ultimate Fetch It Champion",
	"UKC Prefix", "Dock Jumping (Air Dog) United Fetch It Grand Champion", "GSFCH", "United Grand Supreme Fetch It Champion",
	"UKC Prefix", "Drag Racing Flat Race", "UFGCH", "United Flat Racer Grand Champion",
	"UKC Prefix", "Drag Racing Flat Race", "UFCH", "United Flat Racer Champion",
	"UKC Prefix", "Drag Racing Flat Race", "UFR", "United Flat Racer",
	"UKC Prefix", "Drag Racing Flat Race", "UFA", "United Flat Racing Aptitude Test",
	"UKC Prefix", "Drag Racing Steeplechase", "USGCH", "United Steeplechase Grand Champion",
	"UKC Prefix", "Drag Racing Steeplechase", "USCH", "United Steeplechase Racer Champion",
	"UKC Prefix", "Drag Racing Steeplechase", "USR", "United Steeplechase Racer",
	"UKC Prefix", "Drag Racing Steeplechase", "USA", "United Steeplechase Racing Aptitude Test",
	"UKC Prefix", "Lure Coursing", "SGC", "Supreme Grand Coursing Champion",
	"UKC Prefix", "Lure Coursing", "GCB", "Grand Lure Coursing Champion Breed",
	"UKC Prefix", "Lure Coursing", "CCB", "Lure Coursing Champion breed",
	"UKC Prefix", "Lure Coursing", "GCM", "Grand Lure Coursing Champion Mixed",
	"UKC Prefix", "Lure Coursing", "CCM", "Lure Coursing Champion Mixed",
	"UKC Prefix", "Lure Coursing", "CTS", "Coursing Tested Supreme",
	"UKC Prefix", "Lure Coursing", "CTX", "Coursing Tested Excellent",
	"UKC Prefix", "Lure Coursing", "CT", "Coursing Tested",
	"UKC Prefix", "Lure Coursing", "CAS", "Coursing Aptitude Supreme",
	"UKC Prefix", "Lure Coursing", "CAX", "Coursing Aptitude Excellent",
	"UKC Prefix", "Lure Coursing", "CA", "Coursing Aptitude",
	"UKC Prefix", "Nosework", "EN", "Elite Nosework",
	"UKC Prefix", "Nosework", "MN", "Master Nosework",
	"UKC Prefix", "Nosework", "SN", "Superior Nosework",
	"UKC Prefix", "Nosework", "AN", "Advanced Nosework",
	"UKC Prefix", "Nosework", "NN", "Novice Nosework",
	"UKC Prefix", "Nosework", "NCH", "Nosework Champion",
	"UKC Prefix", "Nosework", "ECH", "Elite Nosework Champion",
	"UKC Prefix", "Nosework", "MCH", "Master Nosework Champion",
	"UKC Prefix", "Nosework", "SCH", "Superior Nosework Champion",
	"UKC Prefix", "Nosework", "ACH", "Advanced Nosework Champion",
	"UKC Prefix", "Nosework", "NNCH", "Novice Nosework Champion",
	"UKC Prefix", "Nosework", "NWGC", "Nosework Grand Champion",
	"UKC Prefix", "Nosework", "EGC", "Elite Nosework Grand Champion",
	"UKC Prefix", "Nosework", "MGC", "Master Nosework Grand Champion",
	"UKC Prefix", "Nosework", "SNGC", "Superior Nosework Grand Champion",
	"UKC Prefix", "Nosework", "AGC", "Advanced Nosework Grand Champion",
	"UKC Prefix", "Nosework", "NGC", "Novice Nosework Grand Champion",
	"UKC Prefix", "Nosework", "EE", "Elite Exterior",
	"UKC Prefix", "Nosework", "EV", "Elite Vehicle",
	"UKC Prefix", "Nosework", "EI", "Elite Interior",
	"UKC Prefix", "Nosework", "EC", "Elite Container",
	"UKC Prefix", "Nosework", "ME", "Master Exterior",
	"UKC Prefix", "Nosework", "MV", "Master Vehicle",
	"UKC Prefix", "Nosework", "MI", "Master Interior",
	"UKC Prefix", "Nosework", "MC", "Master Container",
	"UKC Prefix", "Nosework", "SE", "Superior Exterior",
	"UKC Prefix", "Nosework", "SV", "Superior Vehicle",
	"UKC Prefix", "Nosework", "SI", "Superior Interior",
	"UKC Prefix", "Nosework", "SC", "Superior Container",
	"UKC Prefix", "Nosework", "AE", "Advanced Exterior",
	"UKC Prefix", "Nosework", "AV", "Advanced Vehicle",
	"UKC Prefix", "Nosework", "AI", "Advanced Interior",
	"UKC Prefix", "Nosework", "AC", "Advanced Container",
	"UKC Prefix", "Nosework", "NE", "Novice Exterior",
	"UKC Prefix", "Nosework", "NV", "Novice Vehicle",
	"UKC Prefix", "Nosework", "NI", "Novice Interior",
	"UKC Prefix", "Nosework", "NC", "Novice Container",
	"UKC Prefix", "Nosework", "HDGC", "Handler Discrimination Grand Champion",
	"UKC Prefix", "Nosework", "HDCH", "Handler Discrimination Champion",
	"UKC Prefix", "Nosework", "MHDX", "Master Handler Discrimination Excellent",
	"UKC Prefix", "Nosework", "EHDS", "Excellent Handler Discrimination Supreme",
	"UKC Prefix", "Nosework", "MHD", "Master Handler Discrimination",
	"UKC Prefix", "Nosework", "EHD", "Excellent Handler Discrimination",
	"UKC Prefix", "Nosework", "AHD", "Advanced Handler Discrimination",
	"UKC Prefix", "Nosework", "NHD", "Novice Handler Discrimination",
	"UKC Prefix", "Obedience", "UUDX", "United Utility Dog Excellent",
	"UKC Prefix", "Obedience", "GOCH", "United Grand Obedience Champion",
	"UKC Prefix", "Obedience", "UOCH", "United Obedience Champion",
	"UKC Prefix", "Obedience", "UUD", "United Utility Dog",
	"UKC Prefix", "Obedience", "UCDX", "United Companion Dog Excellent",
	"UKC Prefix", "Obedience", "UCD", "United Companion Dog",
	"UKC Prefix", "Rally Obedience", "UROG", "United Rally Obedience Grand Champion",
	"UKC Prefix", "Rally Obedience", "URX", "United Rally Obedience Excellent",
	"UKC Prefix", "Rally Obedience", "UROC", "United Rally Obedience Champion",
	"UKC Prefix", "Rally Obedience", "URO3", "United Rally Obedience Level 3",
	"UKC Prefix", "Rally Obedience", "URO2", "United Rally Obedience Level 2",
	"UKC Prefix", "Rally Obedience", "URO1", "United Rally Obedience Level 1",
	"UKC Suffix", "SPOT", "SPOT-ON", "Specialized Pet Obedience Test - Outstanding Neighbor",
	"UKC Suffix", "SPOT", "SPOT", "Specialized Pet Obedience Test",
	"UKC Prefix", "Weight Pull", "UGWPC1", "United Grand Weight Pull Champion 1",
	"UKC Prefix", "Weight Pull", "UGWPCH", "United Grand Weight Pull Champion",
	"UKC Prefix", "Weight Pull", "UWPCHX", "United Weight Pull Champion Excellent",
	"UKC Prefix", "Weight Pull", "UWPCH", "United Weight Pull Champion",
	"UKC Prefix", "Weight Pull", "UWP", "United Weight Puller",
	"UKC Prefix", "Weight Pull", "UWPS", "United Weight Pull Champion Supreme",
	"UKC Prefix", "Weight Pull", "UWPO", "United Weight Pull Champion Outstanding",
	"UKC Prefix", "Weight Pull", "UWPV", "United Weight Pull Champion Versatile",
	"UKC Prefix", "Weight Pull", "UWPU", "United Weight Pull Ultimate",
	"UKC Prefix", "Weight Pull", "UWPNC1", "United Weight Pull National Champion Division 1",
	"UKC Prefix", "Weight Pull", "UWPNC2", "United Weight Pull National Champion Division 2",
	"UKC Prefix", "Weight Pull", "UEWPCH", "United Elite Weight Pull Champion",
	"UKC Prefix", "Weight Pull", "VPN", "Versatile Puller Novice",
	"UKC Prefix", "Weight Pull", "VPA", "Versatile Puller Advanced",
	"UKC Prefix", "Weight Pull", "VPE", "Versatile Puller Excellent",
	"UKC Prefix", "Weight Pull", "VPU", "Versatile Puller Ultimate",
	"UKC Prefix", "Weight Pull", "AP", "Advanced Puller",
	"UKC Prefix", "Barn Hunt", "RATCHX", "Barn Hunt Champion Excellent",
	"UKC Prefix", "Barn Hunt", "RATCH", "Barn Hunt Champion",
	"UKC Prefix", "Barn Hunt", "RATM", "Master Barn Hunt",
	"UKC Prefix", "Barn Hunt", "RATS", "Senior Barn Hunt",
	"UKC Prefix", "Barn Hunt", "RATO", "Open Barn Hunt",
	"UKC Prefix", "Barn Hunt", "RATN", "Novice Barn Hunt",
	"AKC Suffix", "Canine Good Citizen", "VHMA", "Virtual Home Manners Adult",
	"AKC Suffix", "Canine Good Citizen", "VHMP", "Virtual Home Manners Puppy",
	"NADAC Suffix", "Agility", "IAC", "Intro Agility Certificate",
	"NADAC Suffix", "Agility", "NAC", "Novice Agility Certificate",
	"NADAC Suffix", "Agility", "OAC", "Open Agility Certificate",
	"NADAC Suffix", "Agility", "EAC", "Elite Agility Certificate",
	"NADAC Suffix", "Agility", "O-IAC", "Outstanding Intro Agility Certificate",
	"NADAC Suffix", "Agility", "O-NAC", "Outstanding Novice Agility Certificate",
	"NADAC Suffix", "Agility", "O-OAC", "Outstanding Open Agility Certificate",
	"NADAC Suffix", "Agility", "O-EAC", "Outstanding Elite Agility Certificate",
	"NADAC Suffix", "Agility", "S-IAC", "Superior Intro Agility Certificate",
	"NADAC Suffix", "Agility", "S-NAC", "Superior Novice Agility Certificate",
	"NADAC Suffix", "Agility", "S-OAC", "Superior Open Agility Certificate",
	"NADAC Suffix", "Agility", "S-EAC", "Superior Elite Agility Certificate",
	"NADAC Suffix", "Agility", "IJC", "Intro Jumpers Certificate",
	"NADAC Suffix", "Agility", "NJC", "Novice Jumpers Certificate",
	"NADAC Suffix", "Agility", "OJC", "Open Jumpers Certificate",
	"NADAC Suffix", "Agility", "EJC", "Elite Jumpers Certificate",
	"NADAC Suffix", "Agility", "O-IJC", "Outstanding Intro Jumpers Certificate",
	"NADAC Suffix", "Agility", "O-NJC", "Outstanding Novice Jumpers Certificate",
	"NADAC Suffix", "Agility", "O-OJC", "Outstanding Open Jumpers Certificate",
	"NADAC Suffix", "Agility", "O-EJC", "Outstanding Elite Jumpers Certificate",
	"NADAC Suffix", "Agility", "S-IJC", "Superior Intro Jumpers Certificate",
	"NADAC Suffix", "Agility", "S-NJC", "Superior Novice Jumpers Certificate",
	"NADAC Suffix", "Agility", "S-OJC", "Superior Open Jumpers Certificate",
	"NADAC Suffix", "Agility", "S-EJC", "Superior Elite Jumpers Certificate",
	"NADAC Suffix", "Agility", "ICC", "Intro Chances Certificate",
	"NADAC Suffix", "Agility", "NCC", "Novice Chances Certificate",
	"NADAC Suffix", "Agility", "OCC", "Open Chances Certificate",
	"NADAC Suffix", "Agility", "ECC", "Elite Chances Certificate",
	"NADAC Suffix", "Agility", "O-ICC", "Outstanding Intro Chances Certificate",
	"NADAC Suffix", "Agility", "O-NCC", "Outstanding Novice Chances Certificate",
	"NADAC Suffix", "Agility", "O-OCC", "Outstanding Open Chances Certificate",
	"NADAC Suffix", "Agility", "O-ECC", "Outstanding Elite Chances Certificate",
	"NADAC Suffix", "Agility", "S-ICC", "Superior Intro Chances Certificate",
	"NADAC Suffix", "Agility", "S-NCC", "Superior Novice Chances Certificate",
	"NADAC Suffix", "Agility", "S-OCC", "Superior Open Chances Certificate",
	"NADAC Suffix", "Agility", "S-ECC", "Superior Elite Chances Certificate",
	"NADAC Suffix", "Agility", "TG-I", "Touch n Go Intro",
	"NADAC Suffix", "Agility", "TG-N", "Touch n Go Novice",
	"NADAC Suffix", "Agility", "TG-O", "Touch n Go Open",
	"NADAC Suffix", "Agility", "TG-E", "Touch n Go Elite",
	"NADAC Suffix", "Agility", "O-TG-I", "Outstanding Touch n Go Intro",
	"NADAC Suffix", "Agility", "O-TG-N", "Outstanding Touch n Go Novice",
	"NADAC Suffix", "Agility", "O-TG-O", "Outstanding Touch n Go Open",
	"NADAC Suffix", "Agility", "O-TG-E", "Outstanding Touch n Go Elite",
	"NADAC Suffix", "Agility", "S-TG-I", "Superior Touch n Go Intro",
	"NADAC Suffix", "Agility", "S-TG-N", "Superior Touch n Go Novice",
	"NADAC Suffix", "Agility", "S-TG-O", "Superior Touch n Go Open",
	"NADAC Suffix", "Agility", "S-TG-E", "Superior Touch n Go Elite",
	"NADAC Suffix", "Agility", "TN-I", "Tunnelers Intro",
	"NADAC Suffix", "Agility", "TN-N", "Tunnelers Novice",
	"NADAC Suffix", "Agility", "TN-O", "Tunnelers Open",
	"NADAC Suffix", "Agility", "TN-E", "Tunnelers Elite",
	"NADAC Suffix", "Agility", "O-TN-I", "Outstanding Tunnelers Intro",
	"NADAC Suffix", "Agility", "O-TN-N", "Outstanding Tunnelers Novice",
	"NADAC Suffix", "Agility", "O-TN-O", "Outstanding Tunnelers Open",
	"NADAC Suffix", "Agility", "O-TN-E", "Outstanding Tunnelers Elite",
	"NADAC Suffix", "Agility", "S-TN-I", "Superior Tunnelers Intro",
	"NADAC Suffix", "Agility", "S-TN-N", "Superior Tunnelers Novice",
	"NADAC Suffix", "Agility", "S-TN-O", "Superior Tunnelers Open",
	"NADAC Suffix", "Agility", "S-TN-E", "Superior Tunnelers Elite",
	"NADAC Suffix", "Agility", "WV-I", "Weavers Intro",
	"NADAC Suffix", "Agility", "WV-N", "Weavers Novice",
	"NADAC Suffix", "Agility", "WV-O", "Weavers Open",
	"NADAC Suffix", "Agility", "WV-E", "Weavers Elite",
	"NADAC Suffix", "Agility", "O-WV-I", "Outstanding Weavers Intro",
	"NADAC Suffix", "Agility", "O-WV-N", "Outstanding Weavers Novice",
	"NADAC Suffix", "Agility", "O-WV-O", "Outstanding Weavers Open",
	"NADAC Suffix", "Agility", "O-WV-E", "Outstanding Weavers Elite",
	"NADAC Suffix", "Agility", "S-WV-I", "Superior Weavers Intro",
	"NADAC Suffix", "Agility", "S-WV-N", "Superior Weavers Novice",
	"NADAC Suffix", "Agility", "S-WV-O", "Superior Weavers Open",
	"NADAC Suffix", "Agility", "S-WV-E", "Superior Weavers Elite",
	"NADAC Suffix", "Agility", "HP-I", "Hoopers Intro",
	"NADAC Suffix", "Agility", "HP-N", "Hoopers Novice",
	"NADAC Suffix", "Agility", "HP-O", "Hoopers Open",
	"NADAC Suffix", "Agility", "HP-E", "Hoopers Elite",
	"NADAC Suffix", "Agility", "O-HP-I", "Outstanding Hoopers Intro",
	"NADAC Suffix", "Agility", "O-HP-N", "Outstanding Hoopers Novice",
	"NADAC Suffix", "Agility", "O-HP-O", "Outstanding Hoopers Open",
	"NADAC Suffix", "Agility", "O-HP-E", "Outstanding Hoopers Elite",
	"NADAC Suffix", "Agility", "S-HP-I", "Superior Hoopers Intro",
	"NADAC Suffix", "Agility", "S-HP-N", "Superior Hoopers Novice",
	"NADAC Suffix", "Agility", "S-HP-O", "Superior Hoopers Open",
	"NADAC Suffix", "Agility", "S-HP-E", "Superior Hoopers Elite",
	"NADAC Suffix", "Agility", "BR-I", "Barrelers Intro",
	"NADAC Suffix", "Agility", "BR-N", "Barrelers Novice",
	"NADAC Suffix", "Agility", "BR-O", "Barrelers Open",
	"NADAC Suffix", "Agility", "BR-E", "Barrelers Elite",
	"NADAC Suffix", "Agility", "O-BR-I", "Outstanding Barrelers Intro",
	"NADAC Suffix", "Agility", "O-BR-N", "Outstanding Barrelers Novice",
	"NADAC Suffix", "Agility", "O-BR-O", "Outstanding Barrelers Open",
	"NADAC Suffix", "Agility", "O-BR-E", "Outstanding Barrelers Elite",
	"NADAC Suffix", "Agility", "S-BR-I", "Superior Barrelers Intro",
	"NADAC Suffix", "Agility", "S-BR-N", "Superior Barrelers Novice",
	"NADAC Suffix", "Agility", "S-BR-O", "Superior Barrelers Open",
	"NADAC Suffix", "Agility", "S-BR-E", "Superior Barrelers Elite",
	"AHBA Suffix", "Herding", "JHD", "Junior Herding Dog",
	"AHBA Prefix", "Herding", "HTCH", "Herding Trial Champion",
	"AHBA Suffix", "Herding", "HTD", "Herding Trial Dog",
	"AHBA Suffix", "Herding", "HRD", "Herding Ranch Dog",
	"AHBA Suffix", "Herding", "RLF", "Ranch Large Flock",
	"AHBA Suffix", "Herding", "HTAD", "Herding Trial Arena Dog",
	"AHBA Suffix", "Herding", "HCT", "Herding Capability Test",
]


// test data: 
//let titles =  ["CD", "thing", "REX", "RNX", "RNC", "5839", "AKC", "RN", "CGC", "TKI", "test1", "**ETD**", "**ATD-M**", "ITD-M"];

let titlesInput = document.getElementById("titlesInput");
let titleCheckBtn = document.getElementById("titleCheckBtn");
let titlesHeader = document.getElementById("titlesHeader");
let instructions = document.getElementById("instructions");
let noTitles = document.getElementById("noTitles");
let tableTitles = document.getElementById("tableTitles");

let output = "";
let outputTable = [];
let noDescription = "";

function compareValues(a, b) {
	// for table sorting
	// https://stackoverflow.com/questions/55462632/javascript-sort-table-column-on-click
	// return -1/0/1 based on what you "know" a and b are here.
	return (a < b) ? -1 : (a > b) ? 1 : 0;
}

function sortTable(table, colnum) {
	// get all the rows in this table:
	let rows = Array.from(table.querySelectorAll(`tr`));

	// but ignore the heading row:
	rows = rows.slice(1);

	// set up the queryselector for getting the indicated
	// column from a row, so we can compare using its value:
	let qs = `td:nth-child(${colnum})`;

	// and then just... sort the rows:
	rows.sort((r1, r2) => {
		// get each row's relevant column
		let t1 = r1.querySelector(qs);
		let t2 = r2.querySelector(qs);

		// and then effect sorting by comparing their content:
		return compareValues(t1.textContent, t2.textContent);
	});

	// and then the magic part that makes the sorting appear on-page:
	rows.forEach(row => table.appendChild(row));
}

function clearTable(table) {
	for (let i = table.rows.length - 1; i > 0; i--) {
		table.rows[i].remove()
	}
}

function descriptions(string) {
	let description = "";
	if (string !== "") {
		for (let i = 0; i < titleDescriptions.length; i++) {
			if (string == titleDescriptions[i].toUpperCase()) {
				description += `${titleDescriptions[i - 1]} - ${titleDescriptions[i]} - ${titleDescriptions[i + 1]} \n`;
				outputTable.push({ Type: titleDescriptions[i - 1], Name: titleDescriptions[i], Description: titleDescriptions[i + 1] });
				let row = tableTitles.insertRow();
				let cell1 = row.insertCell(0);
				let cell2 = row.insertCell(1);
				let cell3 = row.insertCell(2);
				let cell4 = row.insertCell(3);

				cell1.innerHTML = `${titleDescriptions[i - 2]}`;
				cell2.innerHTML = `${titleDescriptions[i - 1]}`;
				cell3.innerHTML = `${titleDescriptions[i]}`;
				cell4.innerHTML = `${titleDescriptions[i + 1]}`;
			}
		}
	}

	if (description !== "") {
		output = output.concat(description);
	} else if (string) {
		console.error(`No description for ${string}`);

		let row = noTitles.insertRow();
		let cell1 = row.insertCell(0);
		cell1.innerHTML = `${string}`;
	}
}

tableTitles.querySelectorAll(`th`).forEach((th, position) => {
	th.addEventListener(`click`, evt => sortTable(tableTitles, position + 1));
});

noTitles.querySelectorAll(`th`).forEach((th, position) => {
	th.addEventListener(`click`, evt => sortTable(noTitles, position + 1));
});

titleCheckBtn.addEventListener('click', () => {
	clearTable(tableTitles);
	clearTable(noTitles);
	let titles = titlesInput.value.replace(/[^a-z0-9 -]/gi, '').toUpperCase().split(" ");
	titles.map(descriptions);

	consoleOutput = 0; // 0 = console, 1 = table

	console.log("Table Len:" + noTitles.rows.length);

	if (noTitles.rows.length > 1) {
		noTitles.removeAttribute("hidden");
	} else {
		noTitles.setAttribute("hidden", "hidden");
	}

	if (tableTitles.rows.length > 1) {
		titlesHeader.removeAttribute("hidden");
		tableTitles.removeAttribute("hidden");
		instructions.removeAttribute("hidden");
		instructions.innerText = "Click table headers to sort by that column:";
	} else {
		titlesHeader.setAttribute("hidden", "hidden");
		tableTitles.setAttribute("hidden", "hidden");
		instructions.removeAttribute("hidden");
		instructions.innerText = "No titles were found.";
	}

	if (consoleOutput == 0) {
		console.log(output);
	} else {
		console.table(outputTable, ["Type", "Name", "Description"]);
	}
});