const titleDescriptions = [
	"AKC Prefix","AFC","Amateur Field Trial Champion",
	"AKC Prefix","AGCH","Agility Grand Champion",
	"AKC Prefix","CCH","Bench Show Champion",
	"AKC Prefix","CFC","Coonhound Field Champion",
	"AKC Prefix","CGCH","Coonhound Grand Champion",
	"AKC Prefix","CGF","Coonhound Grand Field Champion",
	"AKC Prefix","CGN","Grand Nite Champion",
	"AKC Prefix","CGW","Grand Water Race Champion",
	"AKC Prefix","CH","Champion",
	"AKC Prefix","CNC","Nite Champion",
	"AKC Prefix","CSG","Supreme Grand Champion",
	"AKC Prefix","CSGF","Supreme Grand Field Champion",
	"AKC Prefix","CSGN","Supreme Grand Nite Champion",
	"AKC Prefix","CSGW","Supreme Grand Water Race Champion",
	"AKC Prefix","CT","Champion Tracker",
	"AKC Prefix","CWC","Water Race Champion",
	"AKC Prefix","CWSG","World Show Champion",
	"AKC Prefix","DC","Dual Champion",
	"AKC Prefix","FC","Field Champion",
	"AKC Prefix","GCH","Grand Champion",
	"AKC Prefix","GCHB","Grand Champion Bronze",
	"AKC Prefix","GCHG","Grand Champion Gold",
	"AKC Prefix","GCHP","Grand Champion Platinum",
	"AKC Prefix","GCHS","Grand Champion Silver",
	"AKC Prefix","GDSC","Gun Dog Stake Champion",
	"AKC Prefix","GAFC","Grand Amateur Field Champion",
	"AKC Prefix","GFC","Grand Field Champion",
	"AKC Prefix","HC","Herding Champion",
	"AKC Prefix","MACH","Master Agility Champion",
	"AKC Prefix","NAC","National Agility Champion",
	"AKC Prefix","NAFC","National Amateur Field Champion",
	"AKC Prefix","NAGDC","National Amateur Gundog Champion",
	"AKC Prefix","NFC","National Field Champion",
	"AKC Prefix","NGDC","National Gundog Champion",
	"AKC Prefix","NOC","National Obedience Champion",
	"AKC Prefix","OTCH","Obedience Trial Champion",
	"AKC Prefix","PACH","Preferred Agility Champion",
	"AKC Prefix","PNAC","Preferred National Agility Champion",
	"AKC Prefix","POC","Preferred Obedience Champion",
	"AKC Prefix","RACH","AKC Rally® Champion",
	"AKC Prefix","RGDSC","Retrieving Gun Dog Stake Champion",
	"AKC Prefix","RNC","AKC Rally® National Champion",
	"AKC Prefix","TC","Triple Champion",
	"AKC Prefix","VCCH","Versatile Companion Champio",
	"AKC Prefix","WNC","World Nite Champion",
	"AKC Suffix","ACT1","Agility Course Test 1",
	"AKC Suffix","ACT2","Agility Course Test 2",
	"AKC Suffix","ACT1J","Agility Course Test 1 Jumpers",
	"AKC Suffix","ACT2J","Agility Course Test 2 Jumpers",
	"AKC Suffix","AJP","Excellent Agility Jumpers With Weaves “A” Preferred",
	"AKC Suffix","ATT","AKC Temperament Test",
	"AKC Suffix","AX","Agility Excellent",
	"AKC Suffix","AXJ","Excellent Agility Jumper",
	"AKC Suffix","AXP","Agility Excellent “A” Preferred",
	"AKC Suffix","BCAT","Fast CAT® BCAT",
	"AKC Suffix","BN","Beginner Novice",
	"AKC Suffix","BN-V","Virtual Beginner Novice",
	"AKC Suffix","CA","Coursing Ability",
	"AKC Suffix","CAA","Coursing Ability Advanced",
	"AKC Suffix","CAX","Coursing Ability Excellent",
	"AKC Suffix","CAX2","Coursing Ability Excellent 2",
	"AKC Suffix","CD","Companion Dog",
	"AKC Suffix","CD-V","Virtual Companion Dog",
	"AKC Suffix","CDX","Companion Dog Excellent",
	"AKC Suffix","CGC","Canine Good Citizen",
	"AKC Suffix","CGCA","AKC Community Canine",
	"AKC Suffix","CGCU","CGCU – Canine Good Citizen Urban",
	"AKC Suffix","CM","Certificate of Merit",
	"AKC Suffix","DCAT","Fast CAT® DCAT",
	"AKC Suffix","EE","Endurance Earthdog",
	"AKC Suffix","FCAT","Fast CAT® FCAT",
	"AKC Suffix","FDC","Farm Dog Certified",
	"AKC Suffix","FTC","FAST Century",
	"AKC Suffix","FTCP","FAST Century Preferred",
	"AKC Suffix","GN","Graduate Novice",
	"AKC Suffix","GO","Graduate Open",
	"AKC Suffix","HI","Herding Intermediate",
	"AKC Suffix","HIAdsc","Herding Intermediate Course A (ducks, sheep, cattle)",
	"AKC Suffix","HIBdsc","Herding Intermediate Course B (ducks, sheep, cattle)",
	"AKC Suffix","HICs","Herding Intermediate Course C (sheep)",
	"AKC Suffix","HS","Herding Started",
	"AKC Suffix","HSAdsc","Herding Started Course A (ducks, sheep, cattle)",
	"AKC Suffix","HSBdsc","Herding Started Course B (ducks, sheep, cattle)",
	"AKC Suffix","HSCs","Herding Started Course C (sheep)",
	"AKC Suffix","HT","Herding Tested",
	"AKC Suffix","HX","Herding Excellent",
	"AKC Suffix","HXAdsc","Herding Advanced Course A (ducks, sheep, cattle)",
	"AKC Suffix","HXBdsc","Herding Advanced Course B (ducks, sheep, cattle)",
	"AKC Suffix","HXCs","Herding Advanced Course C (sheep)",
	"AKC Suffix","JC","Junior Courser",
	"AKC Suffix","JE","Junior Earthdog",
	"AKC Suffix","JH","Junior Hunter",
	"AKC Suffix","JHA","Junior Hunter Advanced",
	"AKC Suffix","JHR","Junior Hunter Retriever",
	"AKC Suffix","JHU","Junior Hunter Upland",
	"AKC Suffix","LCX","Lure Courser Excellent",
	"AKC Suffix","MC","Master Courser",
	"AKC Suffix","ME","Master Earthdog",
	"AKC Suffix","MFB","Master Bronze FAST",
	"AKC Suffix","MFC","Master Century FAST",
	"AKC Suffix","MFG","Master Gold FAST",
	"AKC Suffix","MFP","Master Excellent FAST Preferred",
	"AKC Suffix","MFPB","Master Bronze FAST Preferred",
	"AKC Suffix","MFPC","Master Century FAST Preferred",
	"AKC Suffix","MFPG","Master Gold FAST Preferred",
	"AKC Suffix","MFPS","Master Silver FAST Preferred",
	"AKC Suffix","MFS","Master Silver FAST",
	"AKC Suffix","MH","Master Hunter",
	"AKC Suffix","MHA","Master Hunter Advanced",
	"AKC Suffix","MHR","Master Hunter Retriever",
	"AKC Suffix","MHU","Master Hunter Upland",
	"AKC Suffix","MJB","Master Bronze Jumpers With Weaves",
	"AKC Suffix","MJC","Master Century Jumpers With Weaves",
	"AKC Suffix","MJG","Master Gold Jumpers With Weaves",
	"AKC Suffix","MJP","Master Excellent Jumpers With Weaves Preferred",
	"AKC Suffix","MJPB","Master Bronze Jumper With Weaves Preferred",
	"AKC Suffix","MJPC","Master Century Jumper With Weaves Preferred",
	"AKC Suffix","MJPG","Master Gold Jumper With Weaves Preferred",
	"AKC Suffix","MJPS","Master Silver Jumper With Weaves Preferred",
	"AKC Suffix","MJS","Master Silver Jumpers With Weaves",
	"AKC Suffix","MNH","Master National Hunter",
	"AKC Suffix","MX","Master Agility Excellent",
	"AKC Suffix","MXB","Master Bronze Agility",
	"AKC Suffix","MXC","Master Century Agility",
	"AKC Suffix","MXF","Master Excellent FAST",
	"AKC Suffix","MXG","Master Gold Agility",
	"AKC Suffix","MXJ","Master Excellent Jumpers With Weaves",
	"AKC Suffix","MXP","Master Agility Excellent Preferred",
	"AKC Suffix","MXPB","Master Bronze Agility Preferred",
	"AKC Suffix","MXPC","Master Century Agility Preferred",
	"AKC Suffix","MXPG","Master Gold Agility Preferred",
	"AKC Suffix","MXPS","Master Silver Agility Preferred",
	"AKC Suffix","MXS","Master Silver Agility",
	"AKC Suffix","NA","Novice Agility",
	"AKC Suffix","NAJ","Novice Agility Jumper",
	"AKC Suffix","NAP","Novice Agility Preferred",
	"AKC Suffix","NF","Novice FAST",
	"AKC Suffix","NFP","Novice FAST Preferred",
	"AKC Suffix","NJP","Novice Jumpers With Weaves Preferred",
	"AKC Suffix","OA","Open Agility",
	"AKC Suffix","OAJ","Open Agility Jumper",
	"AKC Suffix","OAP","Open Agility Preferred",
	"AKC Suffix","OF","Open FAST",
	"AKC Suffix","OFP","Open FAST Preferred",
	"AKC Suffix","OGM","Obedience Grand Master",
	"AKC Suffix","OJP","Open Jumpers With Weaves Preferred",
	"AKC Suffix","OM","Obedience Master",
	"AKC Suffix","PAD","Premier Agility Dog",
	"AKC Suffix","PADP","Premier Agility Dog Preferred",
	"AKC Suffix","PAX","Preferred Agility Excellent",
	"AKC Suffix","PCD","Preferred Companion Dog",
	"AKC Suffix","PCDX","Preferred Companion Dog Excellent",
	"AKC Suffix","PDB","Premier Agility Dog Bronze",
	"AKC Suffix","PDBP","Premier Agility Dog Bronze Preferred",
	"AKC Suffix","PDC","Premier Agility Dog Century",
	"AKC Suffix","PDCP","Premier Agility Dog Century Preferred",
	"AKC Suffix","PDG","Premier Agility Dog Gold",
	"AKC Suffix","PDGP","Premier Agility Dog Gold Preferred",
	"AKC Suffix","PDS","Premier Agility Dog Silver",
	"AKC Suffix","PDSP","Premier Agility Dog Silver Preferred",
	"AKC Suffix","PJB","Premier Jumpers Dog Bronze",
	"AKC Suffix","PJBP","Premier Jumpers Dog Bronze Preferred",
	"AKC Suffix","PJC","Premier Jumpers Dog Century",
	"AKC Suffix","PJCP","Premier Jumpers Dog Century Preferred",
	"AKC Suffix","PJD","Premier Jumpers Dog",
	"AKC Suffix","PJDP","Premier Jumpers Dog Preferred",
	"AKC Suffix","PJG","Premier Jumpers Dog Gold",
	"AKC Suffix","PJGP","Premier Jumpers Dog Gold Preferred",
	"AKC Suffix","PJS","Premier Jumpers Dog Silver",
	"AKC Suffix","PJSP","Premier Jumpers Dog Silver Preferred",
	"AKC Suffix","PT","Pre-Trial Tested",
	"AKC Suffix","PUDX","Preferred Utility Dog Excellent",
	"AKC Suffix","PUTD","Preferred Utility Dog",
	"AKC Suffix","RN","AKC Rally® Novice",
	"AKC Suffix","RA","AKC Rally® Advanced",
	"AKC Suffix","RE","AKC Rally® Excellent",
	"AKC Suffix","#RAE","AKC Rally® Advanced Excellent",
	"AKC Suffix","RI","AKC Rally® Intermediate",
	"AKC Suffix","#RM","AKC Rally® Master",
	"AKC Suffix","SBA","Scent Work Buried Advanced",
	"AKC Suffix","SBAE","Scent Work Buried Advanced Elite",
	"AKC Suffix","SBE","Scent Work Buried Excellent",
	"AKC Suffix","SBEE","Scent Work Buried Excellent Elite",
	"AKC Suffix","SBM","Scent Work Buried Master",
	"AKC Suffix","SBME","Scent Work Buried Master Elite",
	"AKC Suffix","SBN","Scent Work Buried Novice",
	"AKC Suffix","SBNE","Scent Work Buried Novice Elite",
	"AKC Suffix","SC","Senior Courser",
	"AKC Suffix","SCA","Scent Work Container Advanced",
	"AKC Suffix","SCAE","Scent Work Container Advanced Elite",
	"AKC Suffix","SCE","Scent Work Container Excellent",
	"AKC Suffix","SCEE","Scent Work Container Excellent Elite",
	"AKC Suffix","SCM","Scent Work Container Master",
	"AKC Suffix","SCME","Scent Work Cotnainer Master Elite",
	"AKC Suffix","SCN","Scent Work Container Novice",
	"AKC Suffix","SCNE","Scent Work Container Novice Elite",
	"AKC Suffix","SE","Senior Earthdog",
	"AKC Suffix","SEA","Scent Work Exterior Advanced",
	"AKC Suffix","SEAE","Scent Work Exterior Advanced Elite",
	"AKC Suffix","SEE","Scent Work Exterior Excellent",
	"AKC Suffix","SEEE","Scent Work Exterior Excellent Elite",
	"AKC Suffix","SEM","Scent Work Exterior Master",
	"AKC Suffix","SEME","Scent Work Exterior Master Elite",
	"AKC Suffix","SEN","Scent Work Exterior Novice",
	"AKC Suffix","SENE","Scent Work Exterior Novice Elite",
	"AKC Suffix","SH","Senior Hunter",
	"AKC Suffix","SHA","Senior Hunter Advanced",
	"AKC Suffix","SHDA","Scent Work Handler Discrimination Advanced",
	"AKC Suffix","SHDAE","Scent Work Handler Discrimination Advanced Elite",
	"AKC Suffix","SHDE","Scent Work Handler Discrimination Excellent",
	"AKC Suffix","SHDEE","Scent Work Handler Discrimination Excellent Elite",
	"AKC Suffix","SHDM","Scent Work Handler Discrimination Master",
	"AKC Suffix","SHDME","Scent Work Handler Discrimination Master Elite",
	"AKC Suffix","SHDN","Scent Work Handler Discrimination Novice",
	"AKC Suffix","SHDNE","Scent Work Handler Discrimination Novice Elite",
	"AKC Suffix","SHR","Senior Hunter Retriever",
	"AKC Suffix","SHU","Senior Hunter Upland",
	"AKC Suffix","SIA","Scent Work Interior Advanced",
	"AKC Suffix","SIAE","Scent Work Interior Advanced Elite",
	"AKC Suffix","SIE","Scent Work Interior Excellent",
	"AKC Suffix","SIEE","Scent Work Interior Excellent Elite",
	"AKC Suffix","SIM","Scent Work Interior Master",
	"AKC Suffix","SIME","Scent Work Interior Master Elite",
	"AKC Suffix","SIN","Scent Work Interior Novice",
	"AKC Suffix","SINE","Scent Work Interior Novice Elite",
	"AKC Suffix","SWA","Scent Work Advanced",
	"AKC Suffix","SWAE","Scent Work Advanced Elite",
	"AKC Suffix","SWD","Scent Work Detective",
	"AKC Suffix","SWE","Scent Work Excellent",
	"AKC Suffix","SWEE","Scent Work Excellent Elite",
	"AKC Suffix","SWM","Scent Work Master",
	"AKC Suffix","SWME","Scent Work Master Elite",
	"AKC Suffix","SWN","Scent Work Novice",
	"AKC Suffix","SWNE","Scent Work Novice Elite",
	"AKC Suffix","T2B","Time 2 Beat",
	"AKC Suffix","T2BP","Time 2 Beat Preferred",
	"AKC Suffix","#TD","Tracking Dog",
	"AKC Suffix","#TDU","Tracking Dog Urban",
	"AKC Suffix","#TDX","Tracking Dog Excellent",
	"AKC Suffix","THD","Therapy Dog Title",
	"AKC Suffix","THDA","Therapy Dog Advanced",
	"AKC Suffix","THDD","Distinguished Therapy Dog",
	"AKC Suffix","THDN","Therapy Dog Novice",
	"AKC Suffix","THDX","Therapy Dog Excellent",
	"AKC Suffix","TKN","Novice Trick Dog",
	"AKC Suffix","TKI","Intermediate Trick Dog",
	"AKC Suffix","TKA","Advanced Trick Dog",
	"AKC Suffix","TKP","Trick Dog Performer​",
	"AKC Suffix","TKE","Trick Dog Elite Performer",
	"AKC Suffix","TQX","Triple Q Excellent",
	"AKC Suffix","TQXP","Triple Q Excellent Preferred",
	"AKC Suffix","UD","Utility Dog",
	"AKC Suffix","#UDX","Utility Dog Excellent",
	"AKC Suffix","VCD1","Versatile Companion Dog 1",
	"AKC Suffix","VCD2","Versatile Companion Dog 2",
	"AKC Suffix","VCD3","Versatile Companion Dog 3",
	"AKC Suffix","VCD4","Versatile Companion Dog 4",
	"AKC Suffix","VER","Versatility",
	"AKC Suffix","#VST","Variable Surface Tracking",
	"AKC Suffix","XF","Excellent FAST",
	"AKC Suffix","XFP","Excellent FAST Preferred",
	"AKC Airedale Terrier Club of America","JFT","Junior Fur Tracker",
	"AKC Airedale Terrier Club of America","SFT","Senior Fur Tracker",
	"AKC Airedale Terrier Club of America","MFT","Master Fur Tracker",
	"AKC American Bloodhound Club","MT","Man Trailer",
	"AKC American Bloodhound Club","MTI","Man Trailer Intermediate",
	"AKC American Bloodhound Club","MTX","Man Trailer Excellent",
	"AKC Basset Hound Club of America","HH","Hunting Hound",
	"AKC Basset Hound Club of America","SHH","Senior Hunting Hound",
	"AKC Basset Hound Club of America","MHH","Master Hunting Hound",
	"AKC Basset Hound Club of America","MHE","Master Hunting Excellent",
	"AKC Dachshund Club of America","HH","Hunting Hound",
	"AKC Dachshund Club of America","SHH","Senior Hunting Hound",
	"AKC Dachshund Club of America","MHH","Master Hunting Hound",
	"AKC Dachshund Club of America","MHE","Master Hunting Excellent",
	"AKC Dalmatian Club of America","CC","Coaching Certificate",
	"AKC Dalmatian Club of America","RD","Road Dog",
	"AKC Dalmatian Club of America","RDX","Road Dog Excellent",
	"AKC Doberman Pinscher Club of America","WAC","Working Aptitude Certificate",
	"AKC Golden Retriever Club of America","CCA","Certificate of Conformation Assessment",
	"AKC Nova Scotia Duck Tolling Retriever Club","WC","Working Certificate",
	"AKC Nova Scotia Duck Tolling Retriever Club","WCI","Working Certificate Intermediate",
	"AKC Nova Scotia Duck Tolling Retriever Club","WCX","Working Certificate Excellent",
	"AKC Petit Basset Griffon Vendeen","PCJH","Parent Club Junior Hunter",
	"AKC Petit Basset Griffon Vendeen","PCSH","Parent Club Senior Hunter",
	"AKC Petit Basset Griffon Vendeen","PCMH","Parent Club Master Hunter",
	"AKC Petit Basset Griffon Vendeen","HH","Hunting Hound",
	"AKC Petit Basset Griffon Vendeen","SHH","Senior Hunting Hound",
	"AKC Petit Basset Griffon Vendeen","MHH","Master Hunting Hound",
	"AKC Petit Basset Griffon Vendeen","MHE","Master Hunting Excellent",
	"AKC Siberian Husky Club of America","SD","Sled Dog",
	"AKC Siberian Husky Club of America","SDX","Sled Dog Excellent",
	"AKC Siberian Husky Club of America","SDO","Sled Dog Outstanding",
	"AKC West Highland White Terrier Club of America","CCA","Certificate of Conformation Assessment",
	"AKC American Rottweiler Club","CS","Carting Started",
	"AKC American Rottweiler Club","CI","Carting Intermediate",
	"AKC American Rottweiler Club","CX","Carting Excellent",
	"AKC American Rottweiler Club","CST","Carting Started Team",
	"AKC American Rottweiler Club","CIT","Carting Intermediate Team",
	"AKC American Rottweiler Club","CXT","Carting Excellent Team",
	"AKC American Bouvier des Flandres Club","NDD","Novice Draft Dog",
	"AKC Bernese Mountain Dog Club of America","NDD","Novice Draft Dog",
	"AKC Belgian Sheepdog Club of America", "NDD", "Novice Draft Dog",
	"AKC Briard Club of America", "NDD", "Novice Draft Dog",
	"AKC Greater Swiss Mountain Dog Club of America", "NDD", "Novice Draft Dog",
	"AKC Mastiff Club of America", "NDD", "Novice Draft Dog",
	"AKC Leonberger Club of America", "NDD", "Novice Draft Dog",
	"AKC American Bouvier des Flandres Club","DD","Draft Dog",
	"AKC Bernese Mountain Dog Club of America", "DD","Draft Dog",
	"AKC Belgian Sheepdog Club of America", "DD","Draft Dog",
	"AKC Briard Club of America", "DD","Draft Dog",
	"AKC Greater Swiss Mountain Dog Club of America", "DD","Draft Dog",
	"AKC Mastiff Club of America", "DD","Draft Dog",
	"AKC Leonberger Club of America", "DD","Draft Dog",
	"AKC American Bouvier des Flandres Club", "NBDD","Novice Brace Draft Dog",
	"AKC Bernese Mountain Dog Club of America", "NBDD","Novice Brace Draft Dog",
	"AKC Belgian Sheepdog Club of America", "NBDD","Novice Brace Draft Dog",
	"AKC Briard Club of America", "NBDD","Novice Brace Draft Dog",
	"AKC Greater Swiss Mountain Dog Club of America", "NBDD","Novice Brace Draft Dog",
	"AKC Mastiff Club of America", "NBDD","Novice Brace Draft Dog",
	"AKC Leonberger Club of America", "NBDD","Novice Brace Draft Dog",
	"AKC American Bouvier des Flandres Club", "BDD", "Brace Draft Dog",
	"AKC Bernese Mountain Dog Club of America", "BDD", "Brace Draft Dog",
	"AKC Belgian Sheepdog Club of America", "BDD", "Brace Draft Dog",
	"AKC Briard Club of America", "BDD", "Brace Draft Dog",
	"AKC Greater Swiss Mountain Dog Club of America", "BDD", "Brace Draft Dog",
	"AKC Mastiff Club of America", "BDD", "Brace Draft Dog",
	"AKC Leonberger Club of America", "BDD", "Brace Draft Dog",
	"AKC St. Bernard Club of America","DD","Draft Dog",
	"AKC St. Bernard Club of America","TDD","Team Draft Dog",
	"AKC Leonberger Club of America", "TDD", "Team Draft Dog",
	"AKC Working Dog","BH","Basic Companion Dog",
	"AKC Working Dog","FH1","Advanced Tracking",
	"AKC Working Dog","FH2","Superior Tracking",
	"AKC Working Dog","IPO1","International Novice Schutzhund",
	"AKC Working Dog","IPO2","International Intermediate Schutzhund",
	"AKC Working Dog","IPO3","International Master Level Schutzhund",
	"AKC Working Dog","SCHH1","Novice Schutzhund",
	"AKC Working Dog","SCHH2","Intermediate Schutzhund",
	"AKC Working Dog","SCHH3","Master Level Schutzhund",
	"AKC Working Dog","SCHHA","Novice Schutzhund A",
	"AKC Working Dog","TC","Temperament Certification",
	"AKC Working Dog","TT","Temperament Test",
	"AKC Working Dog","WDS1","Working Dog Sport 1",
	"AKC Working Dog","WDS2","Working Dog Sport 2",
	"AKC Working Dog","WDS3","Working Dog Sport 3",
	"AKC North American Flyball Association (NAFA)","FDCh","Flyball Dog Champion",
	"AKC North American Flyball Association (NAFA)","FM","Flyball Master",
	"AKC North American Flyball Association (NAFA)","ONYX","ONYX",
	"AKC Barn Hunt Association","CZ8B","Crazy 8s Bronze",
	"AKC Barn Hunt Association","CZ8S","Crazy 8s Silver",
	"AKC Barn Hunt Association","CZ8G","Crazy 8s Gold",
	"AKC Barn Hunt Association","CZ8P","Crazy 8s Platinum",
	"AKC Barn Hunt Association","RATN","Novice Barn Hunt",
	"AKC Barn Hunt Association","RATO","Open Barn Hunt",
	"AKC Barn Hunt Association","RATS","Senior Barn Hunt",
	"AKC Barn Hunt Association","RATM","Master Barn Hunt",
	"AKC Barn Hunt Association","RATCh","Barn Hunt Champion",
	"AKC Barn Hunt Association","RATChX","Barn Hunt Master Champion",
	"AKC North America Diving Dogs (NADD)","DN","Dock Novice",
	"AKC North America Diving Dogs (NADD)","DJ","Dock Junior",
	"AKC North America Diving Dogs (NADD)","DS","Dock Senior",
	"AKC North America Diving Dogs (NADD)","DM","Dock Master",
	"AKC North America Diving Dogs (NADD)","DE","Dock Elite",
	"AKC North America Diving Dogs (NADD)","DNA","Dock Novice Advanced",
	"AKC North America Diving Dogs (NADD)","DJA","Dock Junior Advanced",
	"AKC North America Diving Dogs (NADD)","DSA","Dock Senior Advanced",
	"AKC North America Diving Dogs (NADD)","DMA","Dock Master Advanced",
	"AKC North America Diving Dogs (NADD)","DEA","Dock Elite Advanced",
	"AKC North America Diving Dogs (NADD)","DNX","Dock Novice Excellent",
	"AKC North America Diving Dogs (NADD)","DJX","Dock Junior Excellent",
	"AKC North America Diving Dogs (NADD)","DSX","Dock Senior Excellent",
	"AKC North America Diving Dogs (NADD)","DMX","Dock Master Excellent",
	"AKC North America Diving Dogs (NADD)","DEX","Dock Elite Excellent",
	"AKC North America Diving Dogs (NADD)","AN","Air Retrieve Novice",
	"AKC North America Diving Dogs (NADD)","AJ","Air Retrieve Junior",
	"AKC North America Diving Dogs (NADD)","AS","Air Retrieve Senior",
	"AKC North America Diving Dogs (NADD)","AM","Air Retrieve Master",
	"AKC North America Diving Dogs (NADD)","AE","Air Retrieve Elite",
	"AKC North America Diving Dogs (NADD)","ANA","Air Retrieve Novice Advanced",
	"AKC North America Diving Dogs (NADD)","AJA","Air Retrieve Junior Advanced",
	"AKC North America Diving Dogs (NADD)","ASA","Air Retrieve Senior Advanced",
	"AKC North America Diving Dogs (NADD)","AMA","Air Retrieve Master Advanced",
	"AKC North America Diving Dogs (NADD)","AEA","Air Retrieve Elite Advanced",
	"AKC North America Diving Dogs (NADD)","ANX","Air Retrieve Novice Excellent",
	"AKC North America Diving Dogs (NADD)","AJX","Air Retrieve Junior Excellent",
	"AKC North America Diving Dogs (NADD)","ASX","Air Retrieve Senior Excellent",
	"AKC North America Diving Dogs (NADD)","AMX","Air Retrieve Master Excellent",
	"AKC North America Diving Dogs (NADD)","AEX","Air Retrieve Elite Excellent",
	"AKC UpDog Challenge (Disc Dog)","DDB","Disc Dog Bronze",
	"AKC UpDog Challenge (Disc Dog)","DDBE","Disc Dog Bronze Elite",
	"AKC UpDog Challenge (Disc Dog)","DDG","Disc Dog Gold",
	"AKC UpDog Challenge (Disc Dog)","DDGE","Disc Dog Gold Elite",
	"AKC UpDog Challenge (Disc Dog)","DDP","Disc Dog Platinum",
	"AKC UpDog Challenge (Disc Dog)","DDPE","Disc Dog Platinum Elite",
	"AKC UpDog Challenge (Disc Dog)","DDS","Disc Dog Silver",
	"AKC UpDog Challenge (Disc Dog)","DDSE","Disc Dog Silver Elite",
	"AKC UpDog Challenge (Disc Dog)","DDU","Disc Dog Unobtanium",
	"AKC UpDog Challenge (Disc Dog)","DDUE","Disc Dog Unobtanium Elite",
	"DMWYD Suffix", "NTD", "Novice Trick Dog",
	"DMWYD Suffix", "ITD", "Intermediate Trick Dog",
	"DMWYD Suffix", "ATD", "Advanced Trick Dog",
	"DMWYD Suffix", "ETD", "Expert Trick Dog",
	"DMWYD Suffix", "NTD-M", "Novice Masters Trick Dog",
	"DMWYD Suffix", "ITD-M", "Intermediate Masters Trick Dog",
	"DMWYD Suffix", "ATD-M", "Advanced Masters Trick Dog",
	"DMWYD Suffix", "ETD-M", "Expert Masters Trick Dog",
	"DMWYD Prefix", "TDCH", "Trick Dog Champion",
	"DMWYD Prefix", "TDGCH", "Trick Dog Grand Champion",
	"DMWYD Suffix", "NSD", "Novice Stunt Dog",
	"DMWYD Suffix", "OSD", "Open Stunt Dog",
	"DMWYD Suffix", "PSD", "Proven Stunt Dog",
	"DMWYD Suffix", "SDPro", "Stunt Dog Professional",
	"DMWYD Prefix", "SDCH", "Stunt Dog Champion",
	"DMWYD Prefix", "SDGCH", "Stunt Dog Grand Champion",
	"DMWYD Prefix", "SDGCH2", "Stunt Dog Grand Champion 2",
	"DMWYD Prefix", "SDGCH3", "Stunt Dog Grand Champion 3",
	"DMWYD Suffix", "CCF1", "Canine Conditioning Fitness Level 1",
	"DMWYD Suffix", "CCF2", "Canine Conditioning Fitness Level 2",
	"DMWYD Suffix", "CCF3", "Canine Conditioning Fitness Level 3",
	"DMWYD Suffix", "CCF4", "Canine Conditioning Fitness Level 4",
	"DMWYD Prefix", "CCF-CH", "Canine Conditioning Fitness Champion",
	"DMWYD Suffix", "TC1", "Triple Crown Level 1 (Trick Dog Novice, Novice Stunt Dog, Canine Conditioning Level 1)",
	"DMWYD Suffix", "TC2", "Triple Crown Level 2 (Trick Dog Intermediate, Open Stunt Dog, Canine Conditioning Level 2)",
	"DMWYD Suffix", "TC3", "Triple Crown Level 3 (Trick Dog Advanced, Proven Stunt Dog, Canine Conditioning Level 3)",
	"DMWYD Suffix", "TC4", "Triple Crown Level 4 (Trick Dog Expert, Stunt Dog Professional, Canine Conditioning Level 4)",
	"DMWYD Prefix", "TCCH", "Triple Crown Champion (Trick Dog Champion, Stunt Dog Champion, Canine Conditioning Champion)",
	"DMWYD Suffix", "A+", "Teacher's Pet",
	"DMWYD Suffix", "BTC24", "Beat The Clock 24 Seconds",
	"DMWYD Suffix", "BTC48", "Beat The Clock 48 Seconds",
	"DMWYD Suffix", "BTC60", "Beat The Clock 60 Seconds",
	"DMWYD Suffix", "AKA", "That's My Name",
	"DMWYD Suffix", "AtoZ", "Alphabet Tricks",
	"DMWYD Suffix", "20:1", "20 Dog Tricks: One Prop",
	"DMWYD Suffix", "SOR", "Summer of Ruff",
	"DMWYD Suffix", "SSH", "Summer Scavenger Hunt",
	"DMWYD Suffix", "2K9", "2K-9 RUff Run",
	"DMWYD Suffix", "T3", "Triple Threat",
	"DMWYD Suffix", "AA1", "Animal Actor Level 1 - Photoshot",
	"DMWYD Suffix", "AA2", "Animal Actor Level 2 - Actor",
	"DMWYD Suffix", "AA3", "Animal Actor Level 3 - Film",
	"DMWYD Suffix", "AA4", "Animal Actor Level 4 - Leading Role",
	"DMWYD Suffix", "AA5", "Animal Actor Level 5 - Professional",
	"ASCA Prefix", "CH", "Champion",
	"ASCA Prefix", "A-CH", "Altered Champion",
	"ASCA Suffix", "TD", "Tracking Dog",
	"ASCA Suffix", "TDX", "Tracking Dog Excellent",
	"ASCA Suffix", "TDU", "Tracking Dog Urban",
	"ASCA Suffix", "BN", "Beginner Novice",
	"ASCA Suffix", "GN", "Grad Novice",
	"ASCA Suffix", "CD", "Companion Dog",
	"ASCA Suffix", "CDX", "Companion Dog Excellent",
	"ASCA Suffix", "ODX", "Open Dog Excellent",
	"ASCA Suffix", "UD", "Utility Dog",
	"ASCA Suffix", "UDX", "Utility Dog Excellent (CDX Branch)",
	"ASCA Suffix", "UDX-O", "Utility Dog Excellent (ODX Branch)",
	"ASCA Suffix", "UDX-V", "Utility Dog Excellent Veterans",
	"ASCA Prefix", "OTCH", "Obedience Champion (CDX Branch)",
	"ASCA Prefix", "OTCH2", "Obedience Champion (CDX Branch) 2",
	"ASCA Prefix", "OTCH3", "Obedience Champion (CDX Branch) 3",
	"ASCA Prefix", "OTCH4", "Obedience Champion (CDX Branch) 4",
	"ASCA Prefix", "OTCH5", "Obedience Champion (CDX Branch) 5",
	"ASCA Prefix", "OTCH-O", "Obedience Champion (ODX Branch)",
	"ASCA Prefix", "OTCH-O2", "Obedience Champion (ODX Branch) 2",
	"ASCA Prefix", "OTCH-O3", "Obedience Champion (ODX Branch) 3",
	"ASCA Prefix", "OTCH-O4", "Obedience Champion (ODX Branch) 4",
	"ASCA Prefix", "OTCH-O5", "Obedience Champion (ODX Branch) 5",
	"ASCA Suffix", "RN", "Rally Novice",
	"ASCA Suffix", "RNX", "Rally Novice X",
	"ASCA Suffix", "RNC", "Rally Novice C (Class)",
	"ASCA Suffix", "RA", "Rally Advanced",
	"ASCA Suffix", "RAX", "Rally Advanced X",
	"ASCA Suffix", "RAC", "Rally Advanced C (Class)",
	"ASCA Suffix", "RE", "Rally Excellent",
	"ASCA Suffix", "REX", "Rally Excellent X",
	"ASCA Suffix", "REC", "Rally Excellent C (Class)",
	"ASCA Suffix", "RM", "Rally Master",
	"ASCA Suffix", "RMX", "Rally Master X",
	"ASCA Suffix", "RMC", "Rally Master C (Class)",
	"ASCA Suffix", "REM", "Rally Excellent Masters",
	"ASCA Suffix", "REMX", "Rally Excellent Masters X",
	"ASCA Suffix", "RTX", "Rally Trial X",
	"ASCA Suffix", "RTC", "Rally Trial C (Class)",
	"ASCA Prefix", "RTCH", "Rally Trial Champion",
	"ASCA Prefix", "RTCH2", "Rally Trial Champion 2",
	"ASCA Prefix", "RTCH3", "Rally Trial Champion 3",
	"ASCA Prefix", "RTCH4", "Rally Trial Champion 4",
	"ASCA Prefix", "RTCH5", "Rally Trial Champion 5",
	"ASCA Suffix", "STDd", "Started Ducks",
	"ASCA Suffix", "STDc", "Started Cattle",
	"ASCA Suffix", "STDs", "Started Sheep",
	"ASCA Suffix", "STDdc", "Started Ducks & Cattle",
	"ASCA Suffix", "STDds", "Started Ducks & Sheep",
	"ASCA Suffix", "STDcs", "Started Cattle & Sheep",
	"ASCA Suffix", "STDdcs", "Started Ducks, Cattle & Sheep",
	"ASCA Suffix", "OTDd", "Open Ducks",
	"ASCA Suffix", "OTDc", "Open Cattle",
	"ASCA Suffix", "OTDs", "Open Sheep",
	"ASCA Suffix", "OTDdc", "Open Ducks & Cattle",
	"ASCA Suffix", "OTDds", "Open Ducks & Sheep",
	"ASCA Suffix", "OTDcs", "Open Cattle & Sheep",
	"ASCA Suffix", "OTDdcs", "Open Ducks, Cattle & Sheep",
	"ASCA Suffix", "ATDd", "Advanced Ducks",
	"ASCA Suffix", "ATDc", "Advanced Cattle",
	"ASCA Suffix", "ATDs", "Advanced Sheep",
	"ASCA Suffix", "ATDdc", "Advanced Ducks & Cattle",
	"ASCA Suffix", "ATDds", "Advanced Ducks & Sheep",
	"ASCA Suffix", "ATDcs", "Advanced Cattle & Sheep",
	"ASCA Suffix", "ATDdcs", "Advanced Ducks, Cattle & Sheep",
	"ASCA Suffix", "ATD-Md", "Advanced Trial Dog Multiple Courses Ducks",
	"ASCA Suffix", "ATD-Mc", "Advanced Trial Dog Multiple Courses Cattle",
	"ASCA Suffix", "ATD-Ms", "Advanced Trial Dog Multiple Courses Sheep",
	"ASCA Suffix", "ATD-Mdc", "Advanced Trial Dog Multiple Courses Ducks & Cattle",
	"ASCA Suffix", "ATD-Mds", "Advanced Trial Dog Multiple Courses Ducks & Sheep",
	"ASCA Suffix", "ATD-Mcs", "Advanced Trial Dog Multiple Courses Cattle & Sheep",
	"ASCA Suffix", "ATD-Mdcs", "Advanced Trial Dog Multiple Courses Ducks, Cattle, & Sheep",
	"ASCA Suffix", "ATD-Xd", "Advanced Trial Dog Excellent Ducks",
	"ASCA Suffix", "ATD-Xc", "Advanced Trial Dog Excellent Cattle",
	"ASCA Suffix", "ATD-Xs", "Advanced Trial Dog Excellent Sheep",
	"ASCA Suffix", "ATD-Xdc", "Advanced Trial Dog Excellent Ducks & Cattle",
	"ASCA Suffix", "ATD-Xds", "Advanced Trial Dog Excellent Ducks & Sheep",
	"ASCA Suffix", "ATD-Xcs", "Advanced Trial Dog Excellent Cattle & Sheep",
	"ASCA Suffix", "ATD-Xdcs", "Advanced Trial Dog Excellent Ducks, Cattle, & Sheep",
	"ASCA Suffix", "PATDd", "Post Advanced Trial Dog Ducks",
	"ASCA Suffix", "PATDc", "Post Advanced Trial Dog Cattle",
	"ASCA Suffix", "PATDs", "Post Advanced Trial Dog Sheep",
	"ASCA Suffix", "PATDdc", "Post Advanced Trial Dog Ducks & Cattle",
	"ASCA Suffix", "PATDds", "Post Advanced Trial Dog Ducks & Sheep",
	"ASCA Suffix", "PATDcs", "Post Advanced Trial Dog Cattle & Sheep",
	"ASCA Suffix", "PATDdcs", "Post Advanced Trial Dog Ducks, Cattle & Sheep",
	"ASCA Suffix", "RD", "Ranch Dog",
	"ASCA Suffix", "RTDd", "Ranch Trial Dog Ducks",
	"ASCA Suffix", "RTDc", "Ranch Trial Dog Cattle",
	"ASCA Suffix", "RTDs", "Ranch Trial Dog Sheep",
	"ASCA Suffix", "RTDdc", "Ranch Trial Dog Ducks & Cattle",
	"ASCA Suffix", "RTDds", "Ranch Trial Dog Ducks & Sheep",
	"ASCA Suffix", "RTDcs", "Ranch Trial Dog Cattle & Sheep",
	"ASCA Suffix", "RTDdcs", "Ranch Trial Dog Ducks, Cattle & Sheep",
	"ASCA Suffix", "OFTDd", "Open Farm Trial Dog Ducks",
	"ASCA Suffix", "OFTDc", "Open Farm Trial Dog Cattle",
	"ASCA Suffix", "OFTDs", "Open Farm Trial Dog Sheep",
	"ASCA Suffix", "OFTDdc", "Open Farm Trial Dog Ducks & Cattle",
	"ASCA Suffix", "OFTDds", "Open Farm Trial Dog Ducks & Sheep",
	"ASCA Suffix", "OFTDcs", "Open Farm Trial Dog Cattle & Sheep",
	"ASCA Suffix", "OFTDdcs", "Open Farm Trial Dog Ducks, Cattle & Sheep",
	"ASCA Suffix", "AFTDd", "Advanced Farm Trial Dog Ducks",
	"ASCA Suffix", "AFTDc", "Advanced Farm Trial Dog Cattle",
	"ASCA Suffix", "AFTDs", "Advanced Farm Trial Dog Sheep",
	"ASCA Suffix", "AFTDdc", "Advanced Farm Trial Dog Ducks & Cattle",
	"ASCA Suffix", "AFTDds", "Advanced Farm Trial Dog Ducks & Sheep",
	"ASCA Suffix", "AFTDcs", "Advanced Farm Trial Dog Cattle & Sheep",
	"ASCA Suffix", "AFTDdcs", "Advanced Farm Trial Dog Ducks, Cattle & Sheep",
	"ASCA Suffix", "AFTD-Xd", "Advanced Farm Trial Dog - X Ducks",
	"ASCA Suffix", "AFTD-Xc", "Advanced Farm Trial Dog - X Cattle",
	"ASCA Suffix", "AFTD-Xs", "Advanced Farm Trial Dog - X Sheep",
	"ASCA Suffix", "AFTD-Xdc", "Advanced Farm Trial Dog - X Ducks & Cattle",
	"ASCA Suffix", "AFTD-Xds", "Advanced Farm Trial Dog - X Ducks & Sheep",
	"ASCA Suffix", "AFTD-Xcs", "Advanced Farm Trial Dog - X Cattle & Sheep",
	"ASCA Suffix", "AFTD-Xdcs", "Advanced Farm Trial Dog - X Ducks, Cattle & Sheep",
	"ASCA Prefix", "FTCH", "Farm Trial Champion",
	"ASCA Prefix", "WTCH", "Working Trial Champion",
	"ASCA Prefix", "WTCH-M", "Working Trial Champion Multiple Courses",
	"ASCA Prefix", "WTCH-X", "Working Trial Champion Excellent",
	"ASCA Prefix", "SDCH", "Stockdog Champion",
	"ASCA Suffix", "RS-N", "Regular Standard Novice",
	"ASCA Suffix", "RS-O", "Regular Standard Open",
	"ASCA Suffix", "RS-E", "Regular Standard Elite",
	"ASCA Suffix", "RV-N", "Regular Veteran Novice",
	"ASCA Suffix", "RV-O", "Regular Veteran Open",
	"ASCA Suffix", "RV-E", "Regular Veteran Elite",
	"ASCA Suffix", "RJ-N", "Regular Junior Novice",
	"ASCA Suffix", "RJ-O", "Regular Junior Open",
	"ASCA Suffix", "RJ-E", "Regular Junior Elite",
	"ASCA Suffix", "JS-N", "Jumpers Standard Novice",
	"ASCA Suffix", "JS-O", "Jumpers Standard Open",
	"ASCA Suffix", "JS-E", "Jumpers Standard Elite",
	"ASCA Suffix", "JV-N", "Jumpers Veteran Novice",
	"ASCA Suffix", "JV-O", "Jumpers Veteran Open",
	"ASCA Suffix", "JV-E", "Jumpers Veteran Elite",
	"ASCA Suffix", "JJ-N", "Jumpers Junior Novice",
	"ASCA Suffix", "JJ-O", "Jumpers Junior Open",
	"ASCA Suffix", "JJ-E", "Jumpers Junior Elite",
	"ASCA Suffix", "GS-N", "Gamblers Standard Novice",
	"ASCA Suffix", "GS-O", "Gamblers Standard Open",
	"ASCA Suffix", "GS-E", "Gamblers Standard Elite",
	"ASCA Suffix", "GV-N", "Gamblers Veteran Novice",
	"ASCA Suffix", "GV-O", "Gamblers Veteran Open",
	"ASCA Suffix", "GV-E", "Gamblers Veteran Elite",
	"ASCA Suffix", "GJ-N", "Gamblers Junior Novice",
	"ASCA Suffix", "GJ-O", "Gamblers Junior Open",
	"ASCA Suffix", "GJ-E", "Gamblers Junior Elite",
	"ASCA Suffix", "RS-N-OP", "Regular Standard Novice Outstanding Performance",
	"ASCA Suffix", "RS-O-OP", "Regular Standard Open Outstanding Performance",
	"ASCA Suffix", "RS-E-OP", "Regular Standard Elite Outstanding Performance",
	"ASCA Suffix", "RV-N-OP", "Regular Veteran Novice Outstanding Performance",
	"ASCA Suffix", "RV-O-OP", "Regular Veteran Open Outstanding Performance",
	"ASCA Suffix", "RV-E-OP", "Regular Veteran Elite Outstanding Performance",
	"ASCA Suffix", "RJ-N-OP", "Regular Junior Novice Outstanding Performance",
	"ASCA Suffix", "RJ-O-OP", "Regular Junior Open Outstanding Performance",
	"ASCA Suffix", "RJ-E-OP", "Regular Junior Elite Outstanding Performance",
	"ASCA Suffix", "JS-N-OP", "Jumpers Standard Novice Outstanding Performance",
	"ASCA Suffix", "JS-O-OP", "Jumpers Standard Open Outstanding Performance",
	"ASCA Suffix", "JS-E-OP", "Jumpers Standard Elite Outstanding Performance",
	"ASCA Suffix", "JV-N-OP", "Jumpers Veteran Novice Outstanding Performance",
	"ASCA Suffix", "JV-O-OP", "Jumpers Veteran Open Outstanding Performance",
	"ASCA Suffix", "JV-E-OP", "Jumpers Veteran Elite Outstanding Performance",
	"ASCA Suffix", "JJ-N-OP", "Jumpers Junior Novice Outstanding Performance",
	"ASCA Suffix", "JJ-O-OP", "Jumpers Junior Open Outstanding Performance",
	"ASCA Suffix", "JJ-E-OP", "Jumpers Junior Elite Outstanding Performance",
	"ASCA Suffix", "GS-N-OP", "Gamblers Standard Novice Outstanding Performance",
	"ASCA Suffix", "GS-O-OP", "Gamblers Standard Open Outstanding Performance",
	"ASCA Suffix", "GS-E-OP", "Gamblers Standard Elite Outstanding Performance",
	"ASCA Suffix", "GV-N-OP", "Gamblers Veteran Novice Outstanding Performance",
	"ASCA Suffix", "GV-O-OP", "Gamblers Veteran Open Outstanding Performance",
	"ASCA Suffix", "GV-E-OP", "Gamblers Veteran Elite Outstanding Performance",
	"ASCA Suffix", "GJ-N-OP", "Gamblers Junior Novice Outstanding Performance",
	"ASCA Suffix", "GJ-O-OP", "Gamblers Junior Open Outstanding Performance",
	"ASCA Suffix", "GJ-E-OP", "Gamblers Junior Elite Outstanding Performance",
	"ASCA Suffix", "RS-N-SP", "Regular Standard Novice Outstanding Performance",
	"ASCA Suffix", "RS-O-SP", "Regular Standard Open Superior Performance",
	"ASCA Suffix", "RS-E-SP", "Regular Standard Elite Superior Performance",
	"ASCA Suffix", "RV-N-SP", "Regular Veteran Novice Superior Performance",
	"ASCA Suffix", "RV-O-SP", "Regular Veteran Open Superior Performance",
	"ASCA Suffix", "RV-E-SP", "Regular Veteran Elite Superior Performance",
	"ASCA Suffix", "RJ-N-SP", "Regular Junior Novice Superior Performance",
	"ASCA Suffix", "RJ-O-SP", "Regular Junior Open Superior Performance",
	"ASCA Suffix", "RJ-E-SP", "Regular Junior Elite Superior Performance",
	"ASCA Suffix", "JS-N-SP", "Jumpers Standard Novice Superior Performance",
	"ASCA Suffix", "JS-O-SP", "Jumpers Standard Open Superior Performance",
	"ASCA Suffix", "JS-E-SP", "Jumpers Standard Elite Superior Performance",
	"ASCA Suffix", "JV-N-SP", "Jumpers Veteran Novice Superior Performance",
	"ASCA Suffix", "JV-O-SP", "Jumpers Veteran Open Superior Performance",
	"ASCA Suffix", "JV-E-SP", "Jumpers Veteran Elite Superior Performance",
	"ASCA Suffix", "JJ-N-SP", "Jumpers Junior Novice Superior Performance",
	"ASCA Suffix", "JJ-O-SP", "Jumpers Junior Open Superior Performance",
	"ASCA Suffix", "JJ-E-SP", "Jumpers Junior Elite Superior Performance",
	"ASCA Suffix", "GS-N-SP", "Gamblers Standard Novice Superior Performance",
	"ASCA Suffix", "GS-O-SP", "Gamblers Standard Open Superior Performance",
	"ASCA Suffix", "GS-E-SP", "Gamblers Standard Elite Superior Performance",
	"ASCA Suffix", "GV-N-SP", "Gamblers Veteran Novice Superior Performance",
	"ASCA Suffix", "GV-O-SP", "Gamblers Veteran Open Superior Performance",
	"ASCA Suffix", "GV-E-SP", "Gamblers Veteran Elite Superior Performance",
	"ASCA Suffix", "GJ-N-SP", "Gamblers Junior Novice Superior Performance",
	"ASCA Suffix", "GJ-O-SP", "Gamblers Junior Open Superior Performance",
	"ASCA Suffix", "GJ-E-SP", "Gamblers Junior Elite Superior Performance",
	"ASCA Prefix", "ATCH", "Agility Trial Champion",
	"ASCA Prefix", "ATCH2", "Agility Trial Champion 2",
	"ASCA Prefix", "ATCH3", "Agility Trial Champion 3",
	"ASCA Prefix", "ATCH4", "Agility Trial Champion 4",
	"ASCA Prefix", "ATCH5", "Agility Trial Champion 5",
	"ASCA Suffix", "RSA-N", "Regular Standard Novice",
	"ASCA Suffix", "RSA-O", "Regular Standard Open",
	"ASCA Suffix", "RSA-E", "Regular Standard Elite",
	"ASCA Suffix", "RSDA-N", "Regular Senior Dog Novice",
	"ASCA Suffix", "RSDA-O", "Regular Senior Dog Open",
	"ASCA Suffix", "RSDA-E", "Regular Senior Dog Elite",
	"ASCA Suffix", "JSA-N", "Jumpers Standard Novice",
	"ASCA Suffix", "JSA-O", "Jumpers Standard Open",
	"ASCA Suffix", "JSA-E", "Jumpers Standard Elite",
	"ASCA Suffix", "JSDA-N", "Jumpers Senior Dog Novice",
	"ASCA Suffix", "JSDA-O", "Jumpers Senior Dog Open",
	"ASCA Suffix", "JSDA-E", "Jumpers Senior Dog Elite",
	"ASCA Suffix", "GSA-N", "Gamblers Standard Novice",
	"ASCA Suffix", "GSA-O", "Gamblers Standard Open",
	"ASCA Suffix", "GSA-E", "Gamblers Standard Elite",
	"ASCA Suffix", "JSDA-N", "Gamblers Senior Dog Novice",
	"ASCA Suffix", "JSDA-O", "Gamblers Senior Dog Open",
	"ASCA Suffix", "JSDA-E", "Gamblers Senior Dog Elite",
	"ASCA Suffix", "RSA-N-OP", "Regular Standard Novice Outstanding Performance",
	"ASCA Suffix", "RSA-O-OP", "Regular Standard Open Outstanding Performance",
	"ASCA Suffix", "RSA-E-OP", "Regular Standard Elite Outstanding Performance",
	"ASCA Suffix", "RSDA-N-OP", "Regular Veteran Novice Outstanding Performance",
	"ASCA Suffix", "RSDA-O-OP", "Regular Veteran Open Outstanding Performance",
	"ASCA Suffix", "RSDA-E-OP", "Regular Veteran Elite Outstanding Performance",
	"ASCA Suffix", "JSA-N-OP", "Jumpers Standard Novice Outstanding Performance",
	"ASCA Suffix", "JSA-O-OP", "Jumpers Standard Open Outstanding Performance",
	"ASCA Suffix", "JSA-E-OP", "Jumpers Standard Elite Outstanding Performance",
	"ASCA Suffix", "JSDA-N-OP", "Jumpers Veteran Novice Outstanding Performance",
	"ASCA Suffix", "JSDA-O-OP", "Jumpers Veteran Open Outstanding Performance",
	"ASCA Suffix", "JSDA-E-OP", "Jumpers Veteran Elite Outstanding Performance",
	"ASCA Suffix", "GSA-N-OP", "Gamblers Standard Novice Outstanding Performance",
	"ASCA Suffix", "GSA-O-OP", "Gamblers Standard Open Outstanding Performance",
	"ASCA Suffix", "GSA-E-OP", "Gamblers Standard Elite Outstanding Performance",
	"ASCA Suffix", "GSDA-N-OP", "Gamblers Veteran Novice Outstanding Performance",
	"ASCA Suffix", "GSDA-O-OP", "Gamblers Veteran Open Outstanding Performance",
	"ASCA Suffix", "GSDA-E-OP", "Gamblers Veteran Elite Outstanding Performance",
	"ASCA Suffix", "RSA-N-SP", "Regular Standard Novice Outstanding Performance",
	"ASCA Suffix", "RSA-O-SP", "Regular Standard Open Superior Performance",
	"ASCA Suffix", "RSA-E-SP", "Regular Standard Elite Superior Performance",
	"ASCA Suffix", "RSDA-N-SP", "Regular Veteran Novice Superior Performance",
	"ASCA Suffix", "RSDA-O-SP", "Regular Veteran Open Superior Performance",
	"ASCA Suffix", "RSDA-E-SP", "Regular Veteran Elite Superior Performance",
	"ASCA Suffix", "JSA-N-SP", "Jumpers Standard Novice Superior Performance",
	"ASCA Suffix", "JSA-O-SP", "Jumpers Standard Open Superior Performance",
	"ASCA Suffix", "JSA-E-SP", "Jumpers Standard Elite Superior Performance",
	"ASCA Suffix", "JSDA-N-SP", "Jumpers Veteran Novice Superior Performance",
	"ASCA Suffix", "JSDA-O-SP", "Jumpers Veteran Open Superior Performance",
	"ASCA Suffix", "JSDA-E-SP", "Jumpers Veteran Elite Superior Performance",
	"ASCA Suffix", "GSA-N-SP", "Gamblers Standard Novice Superior Performance",
	"ASCA Suffix", "GSA-O-SP", "Gamblers Standard Open Superior Performance",
	"ASCA Suffix", "GSA-E-SP", "Gamblers Standard Elite Superior Performance",
	"ASCA Suffix", "GSDA-N-SP", "Gamblers Veteran Novice Superior Performance",
	"ASCA Suffix", "GSDA-O-SP", "Gamblers Veteran Open Superior Performance",
	"ASCA Suffix", "GSDA-E-SP", "Gamblers Veteran Elite Superior Performance",
	"ASCA Prefix", "ACE", "ACE Agility Trial Champion",
	"ASCA Prefix", "ACE2", "ACE Agility Trial Champion 2",
	"ASCA Prefix", "ACE3", "ACE Agility Trial Champion 3",
	"ASCA Prefix", "ACE4", "ACE Agility Trial Champion 4",
	"ASCA Prefix", "ACE5", "ACE Agility Trial Champion 5",
	"ASCA Prefix", "VCH", "Versatility Champion",
	"ASCA Prefix", "SVCH", "Supreme Versatility Champion",
	"ASCA Prefix", "PCH", "Performance Champion",
	"ASCA Prefix", "SPCH", "Supreme Performance Champion",
	"ASCA Prefix", "HOF", "Hall of Fame Sire",
	"ASCA Suffix", "DNA-CP", "DNA Certified Profiled",
	"ASCA Suffix", "DNA-VP", "DNA Verified Parentage",
	"ASCA Suffix", "LS-N", "Launch Spring Novice",
	"ASCA Suffix", "LS-A", "Launch Spring Advanced",
	"ASCA Suffix", "LS-E", "Launch Spring Excellent",
	"ASCA Suffix", "LS-M", "Launch Spring Master",
	"ASCA Suffix", "LC-N", "Launch Classic Novice",
	"ASCA Suffix", "LC-A", "Launch Classic Advanced",
	"ASCA Suffix", "LC-E", "Launch Classic Excellent",
	"ASCA Suffix", "LC-M", "Launch Classic Master",
	"ASCA Suffix", "LD-N", "Launch Deluxe Novice",
	"ASCA Suffix", "LD-A", "Launch Deluxe Advanced",
	"ASCA Suffix", "LD-E", "Launch Deluxe Excellent",
	"ASCA Suffix", "LD-M", "Launch Deluxe Master",
	"ASCA Suffix", "LF-N", "Launch Fly Novice",
	"ASCA Suffix", "LF-A", "Launch Fly Advanced",
	"ASCA Suffix", "LF-E", "Launch Fly Excellent",
	"ASCA Suffix", "LF-M", "Launch Fly Master",
	"ASCA Suffix", "LE-N", "Launch Elite Novice",
	"ASCA Suffix", "LE-A", "Launch Elite Advanced",
	"ASCA Suffix", "LE-E", "Launch Elite Excellent",
	"ASCA Suffix", "LE-M", "Launch Elite Master",
	"ASCA Suffix", "LP-N", "Launch Pro Novice",
	"ASCA Suffix", "LP-A", "Launch Pro Advanced",
	"ASCA Suffix", "LP-E", "Launch Pro Excellent",
	"ASCA Suffix", "LP-M", "Launch Pro Master",	
	"ASCA Suffix", "LU-N", "Launch Ultra Novice",
	"ASCA Suffix", "LU-A", "Launch Ultra Advanced",
	"ASCA Suffix", "LU-E", "Launch Ultra Excellent",
	"ASCA Suffix", "LU-M", "Launch Ultra Master",
	"ASCA Suffix", "FS-N", "Fetch It Spring Novice",
	"ASCA Suffix", "FS-A", "Fetch It Spring Advanced",
	"ASCA Suffix", "FS-E", "Fetch It Spring Excellent",
	"ASCA Suffix", "FS-M", "Fetch It Spring Master",
	"ASCA Suffix", "FC-N", "Fetch It Classic Novice",
	"ASCA Suffix", "FC-A", "Fetch It Classic Advanced",
	"ASCA Suffix", "FC-E", "Fetch It Classic Excellent",
	"ASCA Suffix", "FC-M", "Fetch It Classic Master",
	"ASCA Suffix", "FD-N", "Fetch It Deluxe Novice",
	"ASCA Suffix", "FD-A", "Fetch It Deluxe Advanced",
	"ASCA Suffix", "FD-E", "Fetch It Deluxe Excellent",
	"ASCA Suffix", "FD-M", "Fetch It Deluxe Master",
	"ASCA Suffix", "FF-N", "Fetch It Fly Novice",
	"ASCA Suffix", "FF-A", "Fetch It Fly Advanced",
	"ASCA Suffix", "FF-E", "Fetch It Fly Excellent",
	"ASCA Suffix", "FF-M", "Fetch It Fly Master",
	"ASCA Suffix", "FE-N", "Fetch It Elite Novice",
	"ASCA Suffix", "FE-A", "Fetch It Elite Advanced",
	"ASCA Suffix", "FE-E", "Fetch It Elite Excellent",
	"ASCA Suffix", "FE-M", "Fetch It Elite Master",
	"ASCA Prefix", "DTCH-Ls", "Dock Trial Champion Launch Spring",
	"ASCA Prefix", "DTCH-Lc", "Dock Trial Champion Launch Classic",
	"ASCA Prefix", "DTCH-Ld", "Dock Trial Champion Launch Deluxe",
	"ASCA Prefix", "DTCH-Lf", "Dock Trial Champion Launch Fly",
	"ASCA Prefix", "DTCH-Le", "Dock Trial Champion Launch Elite",
	"ASCA Prefix", "DTCH-Lp", "Dock Trial Champion Launch Pro",
	"ASCA Prefix", "DTCH-Lu", "Dock Trial Champion Launch Ultra",
	"ASCA Prefix", "DTCH-Fs", "Dock Trial Champion Fetch It Spring",
	"ASCA Prefix", "DTCH-Fc", "Dock Trial Champion Fetch It Classic",
	"ASCA Prefix", "DTCH-Fd", "Dock Trial Champion Fetch It Deluxe",
	"ASCA Prefix", "DTCH-Ff", "Dock Trial Champion Fetch It Fly",
	"ASCA Prefix", "DTCH-Fe", "Dock Trial Champion Fetch It Elite",
]


// test data: 
//let titles =  ["CD", "thing", "REX", "RNX", "RNC", "5839", "AKC", "RN", "CGC", "TKI", "test1", "**ETD**", "**ATD-M**", "ITD-M"];

let titlesInput = document.getElementById("titlesInput");
let titleCheckBtn = document.getElementById("titleCheckBtn");
let titlesHeader = document.getElementById("titlesHeader");
let instructions = document.getElementById("instructions");
let noTitles = document.getElementById("noTitles");
let tableTitles = document.getElementById("tableTitles");

let output = "";
let outputTable = [];
let noDescription = "";

function compareValues(a, b) {
	// for table sorting
	// https://stackoverflow.com/questions/55462632/javascript-sort-table-column-on-click
	// return -1/0/1 based on what you "know" a and b are here.
	return (a < b) ? -1 : (a > b) ? 1 : 0;
}

function sortTable(table, colnum) {
	// get all the rows in this table:
	let rows = Array.from(table.querySelectorAll(`tr`));

	// but ignore the heading row:
	rows = rows.slice(1);

	// set up the queryselector for getting the indicated
	// column from a row, so we can compare using its value:
	let qs = `td:nth-child(${colnum})`;

	// and then just... sort the rows:
	rows.sort((r1, r2) => {
		// get each row's relevant column
		let t1 = r1.querySelector(qs);
		let t2 = r2.querySelector(qs);

		// and then effect sorting by comparing their content:
		return compareValues(t1.textContent, t2.textContent);
	});

	// and then the magic part that makes the sorting appear on-page:
	rows.forEach(row => table.appendChild(row));
}

function clearTable(table) {
	for (let i = table.rows.length - 1; i > 0; i--) {
		table.rows[i].remove()
	}
}

function descriptions(string) {

	let description = "";

	for (let i = 0; i < titleDescriptions.length; i++) {
		if (string == titleDescriptions[i]) {
			description += `${titleDescriptions[i - 1]} - ${titleDescriptions[i]} - ${titleDescriptions[i + 1]} \n`;
			outputTable.push({ Type: titleDescriptions[i - 1], Name: titleDescriptions[i], Description: titleDescriptions[i + 1] });
			let row = tableTitles.insertRow();
			let cell1 = row.insertCell(0);
			let cell2 = row.insertCell(1);
			let cell3 = row.insertCell(2);

			cell1.innerHTML = `${titleDescriptions[i - 1]}`;
			cell2.innerHTML = `${titleDescriptions[i]}`;
			cell3.innerHTML = `${titleDescriptions[i + 1]}`;
		}
	}

	if (description !== "") {
		output = output.concat(description);
	} else if (string) {
		console.error(`No description for ${string}`);

		let row = noTitles.insertRow();
		let cell1 = row.insertCell(0);
		cell1.innerHTML = `${string}`;
	}
}

tableTitles.querySelectorAll(`th`).forEach((th, position) => {
	th.addEventListener(`click`, evt => sortTable(tableTitles, position + 1));
});

noTitles.querySelectorAll(`th`).forEach((th, position) => {
	th.addEventListener(`click`, evt => sortTable(noTitles, position + 1));
});

titleCheckBtn.addEventListener('click', () => {
	clearTable(tableTitles);
	clearTable(noTitles);
	let titles = titlesInput.value.replace(/[^a-z0-9 -]/gi, '').toUpperCase().split(" ");
	titles.map(descriptions);

	consoleOutput = 0; // 0 = console, 1 = table

	console.log("Table Len:" + noTitles.rows.length);

	if (noTitles.rows.length > 1) {
		noTitles.removeAttribute("hidden");
	} else {
		noTitles.setAttribute("hidden", "hidden");
	}

	if (tableTitles.rows.length > 1) {
		titlesHeader.removeAttribute("hidden");
		tableTitles.removeAttribute("hidden");
		instructions.removeAttribute("hidden");
		instructions.innerText = "Click table headers to sort by that column:";
	} else {
		titlesHeader.setAttribute("hidden", "hidden");
		tableTitles.setAttribute("hidden", "hidden");
		instructions.removeAttribute("hidden");
		instructions.innerText = "No titles were found.";
	}

	if (consoleOutput == 0) {
		console.log(output);
	} else {
		console.table(outputTable, ["Type", "Name", "Description"]);
	}
});